### ISSUE TITLE
Send FleetSync commands

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#18]
send commands (like KAS10 - request status request location etc)

**Comment by caver456** [comment]
next

**Comment by caver456** [comment]
picking up on this issue after Steve found a good free third-party solution with Radtext (https://af9h.morganized.com/radtext)

Initial code is committed in the radtext branch and is ready for testing with the IC trailer radio setup.

The code actually doesn't interact with radtext at all.  Radtext was used to reverse-engineer the necessary com port data.  Those commands were written into radiolog.py, and verified using a com port bridge and a com port monitor (realterm), so, there's no additional external dependency.  Full credit and many thanks to the radtext author and its helpful documentation!

**Comment by caver456** [comment]
testing checklist:

- [ ] at radiolog startup (before clicking OK on initial options dialog)
  - [ ] send text to all
  - [ ] send text to one
  - [ ] send text to list
  - [ ] poll GPS (try a few radios) (hopefully this results in an incoming new entry dialog?)
- [ ] confirm normal incoming FS behavior after initial send test above
- [ ] test send features again after some normal incoming FS actions
  - [ ] send text to all
  - [ ] send text to one
  - [ ] send text to list
  - [ ] poll GPS (try a few radios) (incoming new entry dialog?)

**Comment by caver456** [comment]
Summary from first trial with command trailer radios:
- send text to one radio: success
- send text to all radios: success
- send text to multiple specific radios: fail
- poll for radio location: success
- need to incorporate acknowledge-code-handling
- intermittent failures with message 'no open COM ports were found'

Detials:
- the two-digit plain-text sequence number is not needed: it just shows up as part of the message body.  This brings up an interesting point that we could add a timestamp or such if needed in the future, but, it would be part of the message body - not a separate token.  Regardless, the <sequence> token is not needed.
- the two-digit plain-text sequence number seemed to cause failure of poll-for-GPS, but, that may not be true:  even after pruning the sequence numbers, pollGPS gave no response, but this was probably because the radio had no GPS lock at the time.  Regardless, the <sequence> token is not needed.
- need to come up with an intelligent way to deal with two com ports / two radios.  How do we tell which is which?  How do we tell which one to send to?  Is there a serial port command that can be sent to the radio to query the zone name and channel name?  That would win.  Maybe we should keep track of which com port had the most recent incoming traffic for each device, and send to that port by default?
- when sending to a specific radio (sendText or pollGPS), the mobile radio waits for an incoming 'acknowledge' radio transmission from the portable.  The mobile radio then sends a COM port response to the computer, after some short delay (seems like a second or less).
  - send text to individual radio, successful: COM port response is smiley-0-heart (/x020/x03)
  - send text to individual radio, failure: mobile radio will retry twice (a total of three transmissions) and if no ack transmission was received it will beep loudly for 2 seconds (or so) while displaying <<NO RESPONSE>>, and the COM port response will be smiley-1-heart (/x021/x03)
  - send text to all radios, success OR failure: portables do not attempt to send any ack transmission for broadcasts (sent to all, where fleet ID = 000 and device ID = 0000); either way, COM port response will be smiley-0-heart (/x020/x03).  This could be interpreted as 'I sent the message blindly and I am not expecting any responses, therefore it was successful.'
  - poll GPS (can only be done to an individual radio): COM port response will be smiley-0-heart regardless.  Apparently the portable will only transmit back if it has a GPS lock?  The mobile doesn't wait for an ack transmission, so, it will never give the <<NO RESPONSE>> tone for a GPS poll; there is 'no such thing' as a 'failed' GPS poll.  If the portable had a GPS lock, the smiley-0-heart will be followed by another COM response including $PKLDS, $PKLSH, $GPRMC, $GPGAA (as configured by the radio programming).  Radiolog thinks this is NOT valid fleetsync data because it doesn't have the same preamble (with CID etc) as a normal incoming message, but, radiolog should automatically save this as a new entry with simple message body such as '[Acknowledged GPS location request]' or such.
- intermittent failures with message 'no open COM ports were found' - though normal incoming FS traffic worked fine both before and after the send failures.  Probably just need to re-figure the logic inside the fsSendData function.

TO DO:

- [ ] when sending text to multiple specific radios, wait for acknowledge COM response (1 or 0) before sending to the next radio
- [ ] incorporate ack responses: add new entries, and show popups, both for sendText and for pollGPS
- [ ] deal with two com ports / two radios - see above
- [ ] resolve 'no open com ports were found' failures during fsSendData

**Comment by caver456** [comment]
checklist complete and installed on all three computers (dispatch and Mobile IC 1 and 2).  Closing this ticket, though the next cleanup task will be to find out the right way to merge this back in to the master branch, which is something like 130 commits ahead.  (And then reincorporate fix #48)

**Comment by RadiosPRN** [comment]
Were you able to fix the 'no open COM ports were found' problem? That is what I was getting when testing this several days ago. I was receiving FS data fine but was unable to send at all.

**Comment by caver456** [comment]
I don't think I had that particular issue, but there was a lot of monkeying
with com ports that went on for sure.  Give it a try with the latest on the
radtext branch, and let me know if you still have the problem.

**Comment by RadiosPRN** [comment]
I'm still getting an error saying 'failed on preferred COM port; no alternate COM port available'. I have not checked my radio programming settings yet, I thought there may be an option in there that disables sending FS messages that I need to change.

**Comment by RadiosPRN** [comment]
![photo_2022-05-18_08-36-12](https://user-images.githubusercontent.com/60589990/169040181-47bd83e0-c525-41ba-80ac-581e67235355.jpg)
I am not at our command trailer right now so I'm unable to do any testing. Attached should be a picture I took yesterday when I was playing with it, I don't know if that's helpful.

**Comment by caver456** [comment]
Actually the info farther back in the log file would be good.  The
interesting part is probably when the first radio called in.

The log file is saved in whatever dir you ran radiolog from (probably the
install dir) as radioog_log_yyyy_mm_dd_hhmmss.txt.  Go ahead and attach the
whole file

**Comment by RadiosPRN** [comment]
OK I am planning to be going over there this evening so I'll try to remember to grab that.

**Comment by RadiosPRN** [comment]
Finally got the log this evening
[radiolog_log_2022_05_17_184015.txt](https://github.com/ncssar/radiolog/files/8759020/radiolog_log_2022_05_17_184015.txt)

**Comment by caver456** [comment]
Nothing in that log looks 'broken' - it looks like it sent the instruction
to send the message, but never got back any confirmation.  What behavior do
you notice on the mobile radio when you try to send - anything at all?  Can
you tell if it's actually transmitting, or, is it just sitting there like a
lump?  It's entirely possible there's some radio setting that would prevent
it from sending data, but, I'm not sure what that would be... we didn't
need to specifically set any setting to allow it to send data.  But there
are some radio settings that may affect the stuff, like 'optional
signaling', 'data', etc etc.  Then there are the same questions on the
portable radio side, which don't come in to play unless the mobile sends
but the portable never sends the acknowledge.
Also - what model of mobile are you using?  It's possible that the command
being sent from radiolog just doesn't work with the model of mobile you're
using.
If none of that produces an obvious answer, I'd try installing radtext or
KAS-10 or similar, and seeing if that can send a message successfully.

Calling it a night - let me know if you're able to make any discoveries
based on all that.
-Tom

**Comment by caver456** [comment]
The second thing you noticed (duplicate tab, the first one without
fleetsync menu) is a known bug, with a specific cause.  Most likely, when
you set the callsign after the portable called in, there was a trailing
space.  Can you confirm?  Try again on a fresh radiolog, making a point to
add a trailing space after the portable calls in, like "Team 1 " with a
space after the 1.  That team tab will not have the fleetsync menu.  Then
send a message from the console, and it will generate another tab with the
same name, which does have the fleetsync menu.  For the second part of
confirmation, try a fresh radiolog again, but this time make sure there is
no trailing space when you assign the callsign.  You should just get the
one tab, with the fleetsync menu.
If you can confirm that behavior, then it's an easy fix, I'll get that done
pretty soon here.

Back to the first part of the problem: I'm not sure why it wouldn't be
sending anything.  Here's the snippet when I try to send to a dummy radio,
which appears exactly the same format as when you try to send, which is
good:

[image: image.png]

note that ^B and ^C are how the characters appear in a text editor with
plain text encoding - vi is what I'm using - but in anything that can read
utf-8 encoding, like a powershell terminal, they appear as happy-face and
heart:

[image: image.png]

So, if radtext is working but radiolog is not, unless a different model of
mobile radio expects a different sequence of serial data, then I'm
stumped.  We use TK-5280 mobiles, so it's possible that TK-7180 expects
different data, but I didn't see any place in radtext where you need to
specify the mobile model.

The next level of testing would involve watching the COM port data
generated by radtext.  Unless you already have a known good way to do this,
it would involve setting up a virtual com port bridge (so that outgoing
COM1 traffic becomes incoming COM2 traffic - the free version of Virtual
COM Port Tools by HHD software
https://www.hhdsoftware.com/virtual-serial-ports does the trick on my
computer) and then watching the incoming COM traffic.  Send from radtext
and see what the traffic is, then quit radtext, start radiolog, send from
radiolog and see what the traffic is.  Since Windows only allows one
program to 'claim' a COM port at a time, the real radio won't receive any
of this - we're basically just reverse-engineering what radtext sends, to
make sure radiolog is sending the exact same thing.  If you want to pursue
this, then let me know if you have any questions while setting it up.

**Comment by caver456** [comment]
The extra-spaces-in-callsign-name issues are fixed.  Also I changed the
branch names a bit, the latest branch including all of this fleetsync-send
stuff is now called 'master' instead of 'radtext' and is the default branch
again, so, to get the latest code by downloading, you shouldn't need to
change away from the default branch any more.

Sorry the rest of it will be hard to track down.  It's a definite bug, if
radtext is working but radiolog is not.  We might have access to a 7180
that I can test this out on next week.

**Comment by RadiosPRN** [comment]
So I've finally done a little testing with recording the COM port data. I don't really know what I'm doing but the screenshot is what I'm getting when using RadText and sending a message to 104 1010 with 'Test'.
![Screenshot 2022-06-17 115819](https://user-images.githubusercontent.com/60589990/174335036-95e8541b-6a91-4ccf-98d8-9e103f298f9e.jpg)
I don't know if this is helpful or if it is what you are needing. I am having difficulty getting RadioLog to send the same message when bridging 2 ports. It's giving me an error regarding a valid FleetSync port. Hopefully you already have that info.

In regards to the problem with creating multiple team tabs with the same name it is still doing that when you add a new entry manually and then a radio calls in and you name it the same. For example: if you manually create an entry from Team Alpha and then right click the tab it will have no FS options understandably because it doesn't have a radio ID. If I then key a radio and rename it Team Alpha it will create a second identical tab but this one has FS options. You did seem to clear up part of the problem because sending from the FS console and creating a tab when a radio calls in both results in a single tab with FS options. It only seems to be a problem when manually adding an entry. It also doesn't seem to matter if it has a trailing space or not so that seems to be cleared up, it just needs to merge identical teams when created manually or by radio key up.

**Comment by caver456** [comment]
That is helpful.  Looks like it's the same as what radiolog >should< be
sending.  From the comments in radiolog.py:

    # Serial data format for sendText and pollGPS functions was discovered
by using RADtext
    #    https://radtext.morganized.com/radtext
    #  along with a virtual COM port bridge, and a COM port terminal
emulator to watch the traffic

    # sendText - outgoing serial port data format:
    #
    # <start><length_code><fleet><device><msg><sequence><end>
    #
    # <start> - 02 hex (ascii smiley face)
    # <length_code> - indicates max possible message length, though the
plain text message is not padded to that length
    #   46 hex (ascii F) - corresponds to 'S' (Short - 48 characters)
    #   47 hex (ascii G) - corresponds to both 'L' (Long - 1024 characters)
and 'X' (Extra-long - 4096 characters)
    #   if you send COM port data with message body longer than that limit,
the mobile will not transmit
    # <fleet> - plain-text three-digit fleet ID (000 for broadcast)
    # <device> - plain-text four-digit device ID (0000 for broadcast)
    # <msg> - plain-text message
    # UNUSED: <sequence> - plain-text two-digit decimal sequence identifier
- increments with each send - probably not relevant
    #   NOTE: sequnce is generated by radtext, but, it shows up as part of
the message body on the
    #          receiving device, which is probably not useful.  Interesting
point that we could
    #          add timestamp or such to the message body if needed, but,
this is not a separate token.
    # <end> - 03 hex (ascii heart)
    #
    # examples:
    # broadcast 'test' (short):  02 46 30 30 30 30 30 30 30 74 65 73 74 32
39 03   F0000000test28  (sequence=28)
    # 100:1002 'test' (short):  02 46 31 30 30 31 30 30 32 74 65 73 74 33
31 03   F1001002test31  (sequence=31)

The sequence token is the only thing missing - looks like your install of
radtext is not sending that, and from the notes it's a visible part of the
message body anyway so I probably shouldn't list it as its own token - so
it probably is not relevant here.  Probably just a checkbox somewhere in
the radtext settings.

I see what you mean about not being able to send.  In Windows, each
application that wants a port claims it and locks it so no other
application can use it.  If you can set up two virtual bridges, a COM1-COM2
bridge and a COM3-COM4 bridge, then you could probably get this all to work
- the free version of the bridge tool I'm using doesn't allow more than one
bridge.  I'll try to make a custom testable version of radiolog that can
send blindly, without having to have received a call to wake up the port
first.  Shouldn't be hard to do, and the testability will help for sure.

On the other items, I'm not able to reproduce the issue, but I want to make
sure I'm trying the same thing.  Here's a short screen video of trying it
here, could you take a look and let me know?
https://youtu.be/Zz4IciDrYbY

**Comment by RadiosPRN** [comment]
With the trial version of the software I can do 2 virtual bridges. I'm not 100% sure how I would set it up though to get it to work. I will have to play with that when I am in the trailer again.

On the tabs issue I figured it out by watching your video. When I added a manual entry I simply entered 'Alpha'. When a radio keys up it automatically adds 'Team' and then I added 'Alpha'. This creates 2 tabs with both named 'Alpha' but when I click on the tab and look in the Team column one says 'Alpha' and the other tab column says 'Team Alpha'. I don't know if this is the intended result or not but either way I know what to do to fix it. It might be nice to make so neither (or both) entry adds 'Team' automatically so this problem doesn't come up but not a big deal. Thanks!

**Comment by caver456** [comment]
Actually, got it working with just one bridge, using the radiolog code
as-is.
Basically: use the term program (I'm using RealTerm) to send the data that
mimics an incoming transmission and spawns the new entry dialog.  That way
the port is recognized by radiolog,  Then send a text message and the same
term program will see it.  Realterm can write as well as read.

assuming you are not plugged in to a real radio, and the virtual com port
bridge is running on com1<-->com2:
1) start realterm; set it to use com1 (in the Port tab, select '1' or
'COM1' - on mine, it says '1 = \00000012')
2) start radiolog; you should see in the log that it grabs com2
3) in realterm, go to the 'Send' tab and paste this in the top left field:
I11002001100200110 I11002001100200110
That should appear with a little '02' at the start, and a little '03' at
the end, which could show up as smiley and heart depending on how you are
viewing it, and then that whole thing is repeated.  I think Kenwood does
this to increase the chances of the CID going thru in dodgy reception.  Not
sure if the repetition is strictly necessary.
4) hit 'Send ASCII' to the right of the field you just pasted the stuff
into.

radiolog should open a new entry dialog.  That's good, it means the com
port is now 'valid'.

5) in realterm, go to the Display tab and select Hex[space] under 'Display
As'
6) in radiolog, try sending a text message.

Since radiolog always appends the date and time, mine looks like this:
02 46 31 30 30 32 30 30 31 4A 75 6E 31 37 20 31 34 3A 30 35 20 74 65 73 74
03

The main thing is that it starts with 02 then 46 then the fleet (100='31 30
30') then device (2001='32 30 30 31') then the text (test='4A 75 6E 31)
plus the timestamp text, and ends with 03.

If you can confirm all this on your installation then that would be good,
though, I'm still stumped.  We know that this 02-stuff-03 format is what
radtext sends to your 7180, and we know it works, and we see that radiolog
is sending the same thing as what radtext sends.  Will brainstorm some on
next steps.  Clearly there is some difference between radtext and radiolog.


On the duplicate tab thing, I'll see what a good solution might be - you
shouldn't always have to either type Team or not type Team.  If you could,
try to duplicate the problem with a team name that is a number, like team
101.  I think the code should automatically merge 'team 101' and '101',
actually by automatically prefixing 'team' when you tab out of the callsign
field or click a button.

**Comment by RadiosPRN** [comment]
Running RealTerm I get this format from RadText "F1041010Test" and this from RadioLog "F1041010Jun17 18:12 Test" (the symbols at the beginning and end are not displaying properly).

On the duplicate tab it does automatically populate 'Team' when entering 101. I guess our team is just different in that we use letters instead of numbers. It's not a big deal though now that I know how to deal with it.

**Comment by caver456** [comment]
If you select the hex display format you should be able to tell that the
starting character is 02 and the last is 03 for each.  If that's true, then
yeah I am stumped.  I'll talk with some other gurus around here to see if
anyone knows what could be causing that, and will get back to you sometime
next week.

When the only content of the callsign is a number (of however many digits),
I figured it was safe to forcibly prepend 'Team' all of the time.  But,
when it's not just numbers, it doesn't seem like the same thinking would
work.  We have callsigns like 'Relay' or 'Transport 3' or such.  Still,
there's probably some middle ground to catch more accidental omissions or
inclusions of the word Team, like checking to see if a callsign
with/without 'Team', but otherwise the same, already exists.  Will keep it
on the list of things to address.

**Comment by RadiosPRN** [comment]
My apologies, I should have read the rest of your post better. Hex from RadText:
02 46 31 30 30 31 30 30 30 54 65 73 74 03
and hex from RadioLog:
02 46 31 30 30 31 30 30 30 4A 75 6E 31 38 20 31 30 3A 30 38 20 54 65 73 
74 03
As you said it all seems to be correct. I do want to try it again with the radio when I get a chance. I am wondering if there is a possibility that the data was not getting to the radio for some reason. I had it happen last night when I was testing that I was sending from RadioLog and nothing was showing up in RealTerm, this morning it is showing up again fine so not sure if I had something set wrong in RealTerm or if it could be another problem. I was trying to figure out a way to monitor the COM port in real time to make sure the data is actually getting to the radio and there is not a problem before it gets there. I'll try to do some more testing.

Would it be easy to treat the Change Callsign pop up the same way as the Add Entry box? It only prepends "Team" automatically when the callsign is only a number? We also use other identifiers like Boat, Drone etc. so understand that.

**Comment by caver456** [comment]
Eeenteresting.  Looks like pyserial defaults to one stop bit, and it
doesn't look like the radiolog code tries to specify a different stop bits
count:

https://pyserial.readthedocs.io/en/latest/pyserial_api.html

radiolog.py line 1311:
   self.comPortTryList.append(serial.Serial(portIterable[0]))

But in the kenwood setup doc I put together in 2015, for setting up the
connected mobile radios, it calls for 2:
[image: image.png]

I don't actually have a mobile radio here to test with, but I'm not sure
where the disconnect lies.  Best guess from the above is that the radio is
actually programmed for 1 stop bit and the pic is wrong.

In light of all that, I agree it makes sense to wrap this sub-issue up with
the closing solution to "fiddle around with stop bits".  If you discover
something else, feel free to reopen.
