### ISSUE TITLE
slash in incident name kills everything

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#346]
slash in incident name results in various file save errors but they do not tell the root cause.  Also no data gets saved at all.  Make everything deal gracefully with slashes in incident name, probably just a search-and-replace with underscore or something (ideally, reversible) when incident name is specified

**Comment by robsheldon** [comment]
Filesystems especially are finicky; they can handle most special characters but then you run into an unhappy surprise.

I've made it a matter of habit to regex-replace runs of special characters with a single underscore whenever I'm working with identifiers that touch things like filesystems and databases. So, match: [^A-Za-z0-9_-]+ and replace with '_' (not sure what the syntax is for this in Python).

**Comment by caver456** [comment]
actually don't need to worry about making it reversible, since the unmodified incident name appears as a comment in the saved .csv.  Ahhh.

**Comment by caver456** [comment]
That regex looks like a good idea, will try it out, especially since explicit backslash replacement is a bit tricky.
