### ISSUE TITLE
Suggestion for Config file

### ISSUE THREAD

**Issue by RonRN18** [ncssar/radiolog#348]
In order to keep the primary code universal yet customizable for each agency using the software, I suggest creating a CONFIG file that identifies default variables for each agency. While researching my suggestion, I came across [https://martin-thoma.com/configuration-files-in-python/](https://martin-thoma.com/configuration-files-in-python/) which describes methods of doing this.

 For example, in radiolog.py, lines 1282, 1301, 1425 and 1443 include “NEVADA COUNTY SHERIFF’S\nSEARCH AND RESCUE”. In the CONFIG file there would be a place to identify an agency. Therefore, I could change a variable for agency name from “NEVADA COUNTY SHERIFF’S\nSEARCH AND RESCUE” to “PLACER COUNTY SHERIFF’S\nSEARCH AND RESCUE”. On those lines of radiolog.py, it would replace “NEVADA COUNTY SHERIFF’S\nSEARCH AND RESCUE” with the variable from the CONFIG file. Other variables to include in the CONFIG file could be DATUM, coordinate format and timeout interval; DATUM and coordinate format are not currently variable but the setting could be set in the CONFIG instead of asking at startup. In our county, our default timeout interval is 60 minutes, but the default natively in the program is 30 minutes. I still appreciate the ability to go into settings and vary the timeout interval but setting the default could be set in the CONFIG file. Other variables to be in the CONFIG file include the working directories referred to in lines 503-506, logo file name/location referred to on line 520, clue report fillable PDF file name/location referred to on line 521 and location of GISInternals referred to on line 522. Therefore, the CONFIG file may look something similar to:
```
agencyName=“PLACER COUNTY SHERIFF’S\nSEARCH AND RESCUE”
datum=wgs84
coordinate=utm
timeoutMinutes=60
logo=C:\radiolog\images\PCSOSARlogo.png
clueReport=C:\radiolog\images\PCSO_clueReportFillable.pdf
gisInternalsDir=C:\GISInternals
firstWorkingDir=C:\Users\Default\Documents
secondWorkingDir=S:\RadiologDocuments\
```

From my example, I’m assuming the text for “agencyName” would need to have the “\n” in there to cause SEARCH AND RESCUE to be on the next line. I am also assuming that “timeoutMinutes” will later be multiplied by 60 because I believe the timeout interval is actually in seconds instead of minutes. I’m not sure if each directory “\” needs to be doubled (“C:\\radiolog\\images\\PCSOSARlogo.png”). Lastly, I’m not sure if a second working directory will understand a mapped network drive; in my example, I set a second working directory to a mapped networked NAS drive, I’m hoping it does.

If my suggestion is utilized, radiolog.py can be modified for new features by performing a “git pull” but your specific modifications remain constant.

**Comment by caver456** [comment]
This is great, thanks for looking in to the details.  I may stick with the
.rc file convention which doesn't really look any different than what you
have, just since some .rc files are already in play.  Anyway this topic
will take a while to get completely in place, but obviously it needs to
happen.  If you want to tackle some of it go ahead and do the pull request
thing, though, I am failry novice at github collaboration.

**Comment by caver456** [comment]
planning to tackle this next, since fleetsync device filtering is done

**Comment by caver456** [comment]
Started a new branch 'config'.   Just a framework so far.

**Comment by caver456** [comment]
closing this issue since the config branch got finished and merged
