### ISSUE TITLE
invalid fs data causes no pop-ups

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#358]
see https://photos.app.goo.gl/sDPRqywGThOvO9Xm2

this happens for all incoming transmissions - no popups show up at all, but otherwise everything keeps working; restart of the program with reload of data brought everything back to life (except for the fs lookup table, so each new incoming transmission spawned the change-callsign dialog again - should I have loaded the lookup table separately?)

**Comment by RonRN18** [comment]
Just a curiosity, I have not actually looked at the log when everything was working properly. I know that I have programmed all the radios to transmit _just_ the $PKLDS sentence. I know that $PKLDS sends $GPRMC+Fleet+ID+Status. In the $GPRMC sentence, there is no mention of altitude. What I find odd is that in your log, I am seeing $PKLSH, which sends $GPGLL which _does_ send altitude information. My curiosity is where does the $PKLSH information come from if not sent by the radio?

**Comment by caver456** [comment]
Hi Ron, I need to refresh on al this too and will get back to you then.
