### ISSUE TITLE
Crashing when making an entry

### ISSUE THREAD

**Issue by RonRN18** [ncssar/radiolog#375]
I have just updated our Radiolog software and getting frequent crashes. The odd thing is it is not always reproducable but it is always the same error. The error states: "`AttributeError:'QWidget' object has no attribute 'text'`." When a unit calls in, we get the pop-up asking for us to assign them to a team, which we do. We then enter in their message, such as clicking "Departing IC" and click OK. This is what is prompting this error and Python crashes.

**Comment by caver456** [comment]
from Ron's email 8-12-18 12:27pm:
```
...
line 2703, in newEntryProcessTeam
  self.newTeam(niceTeamName)
line 2855, in newTeam
  self.rebuildTeamHotkeys()
line 2991, in rebuildTeamHotkeys
  callsign=self.ui.tabWidget.tabBar().tabButton(i,QTabBar.LeftSide).text().replace(' ','')
AttributeError: 'QWidget' object has no attribute 'text'
```

**Comment by caver456** [comment]
getting almost the same error trying the latest version on the ncssar dispatch laptop.  The trace output is the same, but, it does not crash.  When you first hit enter to accept a message for a new team (created by keyboard, not by fleetsync), the following things happen:
- the message appears in the main table
- a tab is created for the new team but nothing appears in its tab pane
- the NED stays open - nothing changes in the NED
- then hit enter again, and the NED closes but nothing else changes about the main window
- everything stays responsive

**Comment by caver456** [comment]
guessing that this is due to python version.  Home computer (3.6.1) does not show the error.  SAR laptop (3.4.2) does.  Installing 3.7.0 to try it out.

**Comment by RonRN18** [comment]
When I next get a chance, which will likely be Friday or next Monday, I will look to see which version of Python I have installed. Off the top of my head, I do not recall which version I installed on the comm truck computers. Which version of Python do you run yours on in the field?

**Comment by caver456** [comment]
we have 3.4.2 on our dispatch laptop and it is seeing similar errors to
what you had.  I run 3.6.1 at home with no errors.  Upgrading home system
to 3.7.0 now and if that works out then I will upgrade the dispatch laptop
(with me at home now) and see if the error remains.

**Comment by caver456** [comment]
With 3.7.0 on home computer:
```
PS C:\Users\caver\Documents\GitHub\radiolog> python radiolog.py
7067:fsLoadLookup called: startupFlag=True  fsFileName=None  hideWarnings=False
7067:  trying radiolog_fleetsync.csv
7067:Loading FleetSync Lookup Table from file radiolog_fleetsync.csv
7068:  Opened newly found port COM1
7068:  Opened newly found port COM2
7068:  Opened newly found port COM4
7071:1 - begin fontsChanged
7071:2
7071:1: start of redrawTables
7071:2
7071:3
7071:4
7071:5
7071:6
7071:7: end of redrawTables
7071:3 - end of fontsChanged
```
[press '1' --> NED opens with 'FROM' 'Team 1']
```
7078:newEntryWidget created
7078:tabCount=3 currentIndex=1
7078:clueLog.openDialogCount=0
7078:changeCallsignDialog.openDialogCount=0
7078:subjectLocatedDialog.openDialogCount=0
7078:showing
7078:raising
7078:resetting last mod age for Team 1
```
[Enter to set focus to message field]
[type some goop]
```
7111:resetting last mod age for Team 1
7111:resetting last mod age for Team 1
7112:resetting last mod age for Team 1
```
[Enter to accept the message: all appears normal - main table, new tab with new entry]
```
7113:Accepted
7113:newEntry called with these values:
7113:['2124', 'FROM', 'Team 1', '123', None, '', 1534307078.4807446, None, None, None]
7113:new team: newTeamName=Team 1 extTeamName=team00001 niceTeamName=Team 1 shortNiceTeamName=1
7113:building hotkey tab: callsign=1  hotkey=1
7113:attached callsigns: []
7113:Accepted2
7113:removeTab: count=3 i=1
7113:tabCount=2 currentIndex=1
7113:lowering: count=3
7113:1: called newEntryPost
7113:3
7113:4
7113:5
7113:5.1
7113:5.2
7113:5.2.1
7113:5.2.1.2
7113:5.2.1.2.1
7113:  a: i=1
7113:  b
7113:  c
7113:  d
7113:  e
7113:6
7113:  writing C:\Users\caver\Documents\New_Incident_2018_08_14_212435.csv
7113:7: finished newEntryPost
[type '2' --> NED opens with 'FROM' 'Team 2']
7119:newEntryWidget created
7119:tabCount=3 currentIndex=1
7119:clueLog.openDialogCount=0
7119:changeCallsignDialog.openDialogCount=0
7119:subjectLocatedDialog.openDialogCount=0
7119:showing
7119:raising
7119:resetting last mod age for Team 2
```
[Enter to set focus to message field]
[type some goop]
```
7157:resetting last mod age for Team 2
7157:resetting last mod age for Team 2
7157:resetting last mod age for Team 2
```
[Enter --> CRASH]
```
7159:Accepted
7159:newEntry called with these values:
7159:['2125', 'FROM', 'Team 2', 'asd', None, '', 1534307119.1927416, None, None, None]
7159:new team: newTeamName=Team 2 extTeamName=team00002 niceTeamName=Team 2 shortNiceTeamName=2
Traceback (most recent call last):
  File "radiolog.py", line 3662, in keyPressEvent
    self.accept()
  File "radiolog.py", line 3739, in accept
    self.parent.newEntry(self.getValues())
  File "radiolog.py", line 2697, in newEntry
    self.newEntryProcessTeam(niceTeamName,status,values[1],values[3])
  File "radiolog.py", line 2705, in newEntryProcessTeam
    self.newTeam(niceTeamName)
  File "radiolog.py", line 2857, in newTeam
    self.rebuildTeamHotkeys()
  File "radiolog.py", line 2993, in rebuildTeamHotkeys
    callsign=self.ui.tabWidget.tabBar().tabButton(i,QTabBar.LeftSide).text().replace(' ','')
AttributeError: 'QWidget' object has no attribute 'text'
PS C:\Users\caver\Documents\GitHub\radiolog>
```

**Comment by caver456** [comment]
the tabButton in question a QLabel at the time of the crash, so, not sure why it claims it has no text.  Will have to postpone this til after returning on Sept 3.
```...
7033:setting tab button #2 to  2
7033:tab count=3
7033:tab 1: QLabel
Traceback (most recent call last):
  File "radiolog.py", line 3668, in keyPressEvent
    self.accept()
  File "radiolog.py", line 3745, in accept
    self.parent.newEntry(self.getValues())
  File "radiolog.py", line 2697, in newEntry
    self.newEntryProcessTeam(niceTeamName,status,values[1],values[3])
  File "radiolog.py", line 2705, in newEntryProcessTeam
    self.newTeam(niceTeamName)
  File "radiolog.py", line 2858, in newTeam
    self.rebuildTeamHotkeys()
  File "radiolog.py", line 2998, in rebuildTeamHotkeys
    callsign=button.text().replace(' ','')
AttributeError: 'QWidget' object has no attribute 'text'
PS C:\Users\caver\Documents\GitHub\radiolog>
```

**Comment by caver456** [comment]
After some more debugging, really not sure why the most recent tabButton has a text attribute but all previous ones do not even though their metaObject.className is QLabel.  Confirmed with dir(button).  Possibly a Qt bug, but, at the least it is unstable across different installs and different versions for whatever reason.  So: use the whatsThis attribute of the tab instead of the tabButton attribute.
