### ISSUE TITLE
Open existing log?

### ISSUE THREAD

**Issue by RonRN18** [ncssar/radiolog#376]
Is it possible to re-open an existing log? I know if there is a crash and Python did not shut down properly, it usually can open what was open prior to crashing, but is there a way to intentionally open a log that was closed down properly?

**Comment by caver456** [comment]
Yeah, use f4.  Or f6 to grab the previous one.

**Comment by caver456** [comment]
let me know if it is OK to close this one.

**Comment by RonRN18** [comment]
Yes... I guess I didn't look hard enough... it works.
_____________________________________
Ron Webb
