### ISSUE TITLE
better layout for large number of callsigns

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#391]
related to #328 (better scrolling in team tab bar) but this topic is bigger: it's not clear that one horizontal line of tabs is the best type of display.  Need to make sure full callsigns are visible along with their hotkeys, but, with a lot of callsigns, horizontal may not work.  Stacked rows of tabs?  Vertical instead of horizontal?  Smaller font?

**Comment by caver456** [comment]
Came up again during a large campaign search.  Reported from the operator:

"When we have a large/mutual aid search with many teams, can we make the tabs wrap instead of scroll?  I was difficult to see the teams behind the scroll arrow and sometimes actually difficult to click the scroll arrow... "

Needs some fiddling.  Maybe collapsible groups of tabs or such?

**Comment by caver456** [comment]
This came up again during another campaign search.  Time to stop kicking this can down the road.

The multiple-rows-of-tabs thing is really not great, like in the Windows file properties dialog - it's pretty confusing when you click a tab in an upper row and all of a sudden the stuff under the mouse changes on you - 'wait, what the heck just happened?'.  And, looks like Qt can't / won't do that natively, at least as of a few years back:

https://forum.qt.io/topic/94815/qtabwidget-how-to-display-labels-over-multiple-rows

But, it might be the only decent way to accomplish this.  There might be some ways to make it a bit better.  Ideas:
- dim the upper row(s)
- animate the vertical movement of the entire row when an upper-row tab is clicked
- when an upper-row tab is clicked, move the cursor vertically so that it stays over the tab that was clicked

**Comment by caver456** [comment]
some success with angled tabs, but the clickable area is still a hidden horizontal row of rectangles across the top of the tabbar area:

![image](https://user-images.githubusercontent.com/18752102/213883997-c2772ff9-3e82-4172-b181-d04becc6052b.png)

There are other pitfalls to this angled approach: the vertical space required to draw all the tabs is determined by font size, angle, and longest label.  This could leave a lot of unused space if only a few tabs are length.  Also, it's not quite as readable as horizontal labels.

Should think more about the stack-of-rows before pursuing the angled tabs further.

**Comment by caver456** [comment]
Big dilemma.  Multi-row tabs have tons of usability issues too - this page spells them out with a great discussion.  

http://hallofshame.gp.co.at/tabs.htm

The worst is probably the issue with different row widths due to different number of tabs per row - search for 'webforms' at the link above.

Angled is rough.  Stacked is fugly.  Both are confusing.

How bout option #C: use the three-dots at the left of the tabbar (which currently shows up when you hide a tab) to display a simple vertical list of all tabs on hover (with status colors).  When you mouse over a certain callsign in that list, the tabbar is scrolled so that the hovered tab is selected.

The hovered three-dots menu could also show a status summary, i.e. how many teams are still in the field.

No futzing with the tabbar... sounds appealing...

**Comment by caver456** [comment]
If a team tab that is not currently on the screen needs attention (timed out, about to timeout, standby, waiting for transport - any of the flashing status colors) then flash that same color in the three-dots icon.  If the only flashing teams are currently displayed, or there are no flashing teams, then don't flash the three-dots icon or its background.

**Comment by IanBillings** [comment]
I think a sidebar with callsigns listed down vertically would be a good way to handle it, you could could have the ability to create groups for different sectors or areas. Could eventually have columns added for status/timeout/etc

**Comment by caver456** [comment]
Hmm, a permanent sidebar (part of the main window) has some pros and cons versus a popup.  Mainly looking at a popup for now - will do a VERY preliminary commit in a little while.  Will definitely think on the sidebar-as-main-window-widget idea.  Thanks.

**Comment by caver456** [comment]
In recent versions, the main window resizes / widens, apparently without limit (wider than two screens and still growing) to fit the tabbar as more callsigns are added.  In a test from May 11 2022, the window did not grow, and instead scrollbars showed up as more callsigns are added.  Need to figure out how to stop the window from growing.  Check old versions to find out what the exact change was.

**Comment by caver456** [comment]
Did a full binary search of revisions to find out where the change happens - it was Dec 4 2022, due to this one-line change, setting setUsesScrollButtons from True to False, which is spelled out very clearly in the QTabWidget docs:

self.tabWidget.setUsesScrollButtons(False)

So - what we'd really like to do is prevent expansion but not show the scrollbars - or, at least figure out a better manner to indicate there are more tabs on the right side of the tab bar - maybe show the three-dots at the right side in addition to the left side?

The QTabWidget docs for usesScrollArrows point to the style enum bit QStyle::SH_TabBar_PreferNoArrows.  The only docs on that say "Whether a tab bar should suggest a size to prevent scroll arrows."

There are some other interesting QStyle enums:

PM_TabBarScrollButtonWidth
PM_TabBar_ScrollButtonOverlap
SH_TabBar_ElideMode
SH_TabBar_AllowWheelScrolling
SE_TabBarTearIndicatorRight
SE_TabBarScrollLeftButton
SE_TabBarScrollRightButton
SE_TabBarTabLeftButton
SE_TabBarTabRightButton

Looks like QProxyStyle is the way to change these values.  Need to RTFM some more on how to make use of these values.

**Comment by caver456** [comment]
Moving forward with usesScrollArrows True.  Note that leaving it at the default (non-boldface property name in the Qt Designer property editor) isn't sufficient, even though it shows it as True (checked) - since probably the stylesheet overrides it (not really sure). Toggling the checkbox off then on again in Qt Designer sets the property name to boldface which means it will be explicitly written to the .ui file as 'True'.
Definitely need to figure out a better display, probably using QProxyStyle as above, but, that can be done later in this issue:
![image](https://user-images.githubusercontent.com/18752102/215145120-7aaf3c0b-a022-42bb-8f9e-46b00b6d6557.png)

**Comment by caver456** [comment]
Now that the popup seems to be the winning choice, it's time to make a checklist of desired features:

- [ ] callsigns list area
  - [ ] narrow layout - as narrow as possible
  - [ ] color code each entry by status - see what looks good - maybe not the whole background - maybe a square to the right or left of the text
  - [ ] show hidden tabs in square brackets, and/or italic, and/or gray font
  - [ ] allow unhide hidden tabs by some click action on the callsign - context menu, or, just a left click which would normally select the tab in the tabbar, but could intercept and prompt the user as to whether they want to unhide the tab, then unhide and select if so
- [ ] summary area
  - [ ] as narrow as possible
  - [ ] show number of teams per status
  - [ ] show number of teams not at IC
- [ ] behavior
  - [ ] popup on hover, close on mouse out
  - [ ] location: same left edge as main window; vertically centered
  - [ ] size: vertically expanding until screen height, then adding additional column(s) of callsigns
  - [ ] tabbar overflow: leave usesScrollArrows at True to prevent main window expansion as number of callsigns grows; figure out a good way to do the UI; maybe add the three-dots icon on the right of the tabbar as needed with the same behavior as on the left

The 'actions' area - unhide hidden tab, etc - could probably be eliminated, in favor of context menu on each callsign

**Comment by caver456** [comment]
I ain't a math major, but...
![image](https://user-images.githubusercontent.com/18752102/215291204-aca6d0cd-6e78-476e-a7f5-64c212cd85de.png)

**Comment by caver456** [comment]
Colors and blinking are working, but, some refactor should really be done for these reasons:
- increase performance by getting rid of stylesheets for team tabs in the tabbar
- increase performance by doing all of the tab coloring work in just one function, rather than repeating a lot of updateTeamTimers code in teamTabsPopup.resizeEvent
- reduce redundant appearance definitions in statusStyleDict and statusAppearanceDict

**Comment by caver456** [comment]
After a few more cleanup items are done, it's probably a good idea to investigate QDockWidget.  Looks like this might solve some of the focus issues as well as giving a better look and feel.  Demo videos of QDockWidget look pretty nice.  Maybe an animated open on mouse over the three dots, animated close on mouse out (which could be overridden by dragging the dock outside the window and/or with a pin icon to leave it open and move other widgets around it).

**Comment by caver456** [comment]
QDockWidget seems to work ok - but - might get a better look and feel by having an actual overlapping sidebar that shows and widens (with animation) when hovering on the three-dots.  Try overlapping widgets with QGridLayout.

**Comment by caver456** [comment]
Good progress.  The last few comments are stale: the animated-reveal-overain-sidebar doesn't need to be in a QGridLayout - it just needs to be a child of the main window, and its position can be animated, to effectively slide it outside the main window to hide it, and slide it into the main window to show it.

Now, there's an interesting key press focus wackiness issue: key presses are handled by the main window as usual, until clicking in the team tabs table area of the sidebar; after that, key presses are not sent to the main window or even to the sidebar, until clicking in the summary area of the sidebar which restores normal keypress behavior.  Probably just need to set focus policies to NoFocus or such.

[housekeeping: I should really be keeping these notes in a pull request so that the commits are seen in the same sequence as the comments; will think about doing that for future issues; for this issue, will keep the comments here to have them all in one place.]

**Comment by caver456** [comment]
Yeah, focus problem solved, setting to NoFocus was the ticket.  No need for keyPressEvent in the teamTabsPopup class.  Also cleaned up selectability and editability of both tables in the sidebar.

**Comment by caver456** [comment]
Planning to work on this issue now, since the NXDN NexEdge work is done for now with 3.8.0.

**Comment by caver456** [comment]
merged master into this branch

**Comment by johnpictin** [comment]
I had a thought about how you might change the display output to better
accommodate the number of tabs. Why not employ a second monitor or a
background window. Use one monitor/window to hold the complete log
currently in the upper frame. On the second monitor/window display each
added team as a tab or hit box. Once the row fills up wrap a second row.
Between the rows allow space for three or four lines of text to appear.
This will allow you to select a team and see the last three entries without
disrupting the rest of the display. There wouldn't be any floating menus
like the multi line Windows ones referenced earlier. As focus is changed
that team should be highlighted along with the 3 or 4 lines of text. This
could also potentially allow for selection of teams via a touchscreen panel
and using touchscreen input input on the NED for quick input of canned
entries. Thus only text input would require the keyboard. Using a larger
format monitor rotated into portrait mode would maximize the number of
teams visible.

If that isn't enough, what about separating teams into groupings by certain
status types? Teams in the field are on one page. When they return to the
ICP their tab moves to the AT ICP page. Teams in transport could be on a
third page but i think two pages is enough to start.. The available pages
could be selected by chosing the appropriate page from a nav bar at the top
or bottom of the screen. Or a hotkey. If a team has an alert or condition,
like nearing or exceeding a timeout, the heading on active field team page
would flash in the appropriate color as well as the team tab/hit box.

Just some ideas from outside of the box.

John

**Comment by caver456** [comment]
Thanks for the ideas - I've got quite a bit of momentum on the current scheme, pretty close to the finished product, have been using the checklist on the Jan 28 comment to keep track of final tasks.  After that is buttoned up, I'll probably turn it into 3.9.0.  You can revisit the ideas then to see which ones still make sense going forward.

**Comment by caver456** [comment]
Getting pretty close.  In addition to the checklist above, here are a few visual bugs to clear up:
![image](https://github.com/ncssar/radiolog/assets/18752102/86f3e12b-a710-4e49-ab35-d9b23829b772)

- [ ] why the extra column?
- [ ] why the extra row in the summary section?
- [ ] enabling team hotkeys causes the main window to get wider (when there are more teams than fit in the tab bar), probably because teamHotkeysWidget doesn't know how to chop itself when its visibility is toggled

**Comment by caver456** [comment]
To address the third checkbox above (enabling team hotkeys causes the main window to get wider), at the same time as hopefully addressing the tabbar overflow issue: try putting the tabbar and the hotkeys layout into a horizontal QScrollArea.

Doing this in designer is a bit tricky.  Here's the existing object structure:
![image](https://github.com/ncssar/radiolog/assets/18752102/9ce2f0e9-54a0-474f-83c6-545735bed3a8)

**Comment by caver456** [comment]
Can't put the entire tabWidget in a scroll area, since we just want to scroll the tab bar but not the tab contents (the table).
(need to investigate the code - what's tableView vs tabWidget?  Which one holds the actual team log table?  If tableView shows the team log, and tabWidget doesn't show anything below the tab bar, then maybe the idea above could still work.

If not / if tabWidget can't live in a scroll area, here are two other ideas:
- add the team hotkeys labels as part of the tab bar tab layout, instead of having a different widget for the team hotkeys
OR
- put the team hotkeys widget in its own scroll area, to be kept in sync with the tab bar using code

**Comment by caver456** [comment]
tabWidget holds the team log table; turns out that tableView is distracting the way it's listed in the designer object inspector: 'tableView' is actually the main log, above the splitter.

So, plan A won't work: the scrollbar affects the team log table too, which is pretty funky:
![image](https://github.com/ncssar/radiolog/assets/18752102/d473c8cc-1417-46a5-9880-b3d7dbf95623)

**Comment by caver456** [comment]
For the first of the three checkboxes a few comments back 'why the extra column?' - Unfortunately I couldn't figure out the 'right' way to automatically resize the popup width based on the total width of team tabs columns (after resizeToContents), so, just adding up the required post-resized widths of all columns, then setting the fixed dialog width to the greater of that number or the initial width (set in designer to contain the summary table nicely) did the trick, apparently.  More testing needed but this seems to do the trick for now.  Note that it wasn't actually showing an extra column, based on gridlines, but, the popup width was too big.  This appears to be solved with the total-of-required-post-resize-widths method.

**Comment by caver456** [comment]
Noticed a new lag upon accepting first new entry of a new team; lag seems to increase with team count (about a second at 25 teams); lag is not there for subsequent entry of an existing team.  This is just more evidence that a refactor is required. 

Probably related to these lines in the transcript:

```
165358:Accepted
165358:newEntry called with these values:
165358:['1653', 'FROM', 'Team 22', 'STARTING ASSIGNMENT', None, 'Working', 1690674836.8272939, None, None, None]
165358:Accepted2
165358:sidebar show
165358:showEvent called; initial height = 602
165358:theList:['Team 1', 'Team 2', 'Team 3', 'Team 4', 'Team 5', 'Team 8', 'Team 9', 'Team 10', 'Team 11', 'Team 12', 'Team 13', 'Team 14', 'Team 15', 'Team 16', 'Team 17', 'Team 18', 'Team 19', 'Team 20', 'Team 21', 'Team 22', 'Team 63434q34adfasfdsd', 'Team 7khsdfjgkhsdfjgkhsldkfhs;dkfjh;sakdjfh;kjh']
165358:list length = 22   displayedRowCount=11  rowHeight=37
165358:about to resize to new height 639
165358:  but that would be too tall; exiting the loop
165358:final displayedRowCount=11 
```

**Comment by caver456** [comment]
similar to the fix for team table width, by setting the fixed with to the sum of column widths: setting the fixed summary table height to the sum of row heights gets rid of the extra space at the bottom of the table, and resolves bottom-row-height clipping issues too.  Font sizes and row heights were also cleaned up in designer.

**Comment by caver456** [comment]
major refactor committed, see commit comments for details; still need to diagnose lag issues:
- lag at accept on first entry for new team, increasing with team count - about a second at 25 teams, 2+ seconds at 50 teams` - between ‘extTeamNameList after sort’ and ‘next available hotkey’ - this lag DOES still exist after restart and load of 50 teams but is only ~1 second at 52 teams
- lag on first number keypress to open new entry - not noticeable <30 teams or so, between ‘openNewEntry called:key=’ and ‘newEntryWidget __init__ called’ - but this lag does NOT exist after restart and load of 50 teams

**Comment by caver456** [comment]
Confirmed that all of the lag behavior from the previous comment exists in 3.7.0 - so, it’s not due to sidebar code.  Will file separate issues on both of those (if not already filed) but will move forward with this issue - check over all comments to make sure everything is addressed, do some final checking, then merge the branch and close the issue.

**Comment by caver456** [comment]
After adding the issues mentioned above, feels like the one remaining item to address before closing this issue is flashing status colors of tabs that are not currently visible in the tabBar, as in [this comment above](https://github.com/ncssar/radiolog/issues/391#issuecomment-1399348093).

**Comment by caver456** [comment]
blinking three-dots is done in recent commit; but as usual there's always one more item to take care of: when there are enough tabs to cause a scroll, make sure the three-dots icon >and a solid background< stay opaque on top of tabs, to improve visibility.  Avoid this:
![image](https://github.com/ncssar/radiolog/assets/18752102/549d8615-ab50-457e-adef-27efb245cb64)

Maybe this is just autoFillBackground or such?  Otherwise, the icon image file itself could be edited to have an opaque background rather than transparent.

**Comment by caver456** [comment]
An opaque button is one option that seems to be workable; another option that seems to work is to shift the tabbar rightwards with a styleSheet, QTabWidget::tab-bar left:20px or such.

BUT: when the tab is wider than the main window, and scroll bars are used, either option looks a bit strange when the tab bar is all the way left, vs when it's been scrolled some to the right.  It would be best to have the leftmost shown tab at the same x-coordinate in either case.  It's farther left when the tab bar has been scrolled some to the right.  Why?
(the button is darker gray for testing, in order to show its extents)
![image](https://github.com/ncssar/radiolog/assets/18752102/4a5ec0d5-db7f-402f-a854-72ccfaabc366)
![image](https://github.com/ncssar/radiolog/assets/18752102/fffb7e4f-c078-4a47-ace5-60705bb013bf)

**Comment by caver456** [comment]
Got a solution that looks good in recent commit.  Closing this issue for now, will merge to master.  Could be made even better going forward, probably by [making the qtabbar a completely separate widget](https://stackoverflow.com/a/30067364/3577105) which might solve several things including the team hotkeys display when scrolled.
