### ISSUE TITLE
install instructions should have formatting details for radiolog.cfg

### ISSUE THREAD

**Issue by kennethkeim** [ncssar/radiolog#407]
I would like to add a few details to the instructions regarding the format of radiolog.cfg, mainly just make a note that the first line of the file needs to be: "[RadioLog]". We just got it to work, but were a little confused until we found the problem.

**Comment by RonRN18** [comment]
I am trying to find where my original template for the radiolog.cfg file originated... obviously, I got it from Tom, but I don't remember. Below is MY configuration file for Placer County (adjacent to Tom's Nevada County):

`[RadioLog]

# This is the RadioLog local configuration file.

# Customize this file for your team's needs; the
#  rest of the published radiolog code should not
#  change from team to team.

# This file will be read from:
#     <radiolog>/local/radiolog.cfg
#  where <radiolog> is the main radiolog install path
#   which contains radiolog.py

# - the first line of this file must be [RadioLog]
# - blank lines and lines that start with a pound
#    sign (#) are ignored
# - do not use quotes around strings in this file
# - default values (the values that will be used
#    by radiolog if this file does not set the value)
#    are described in comments below
# - to set a different value, uncomment the setting
#    line and set its value as needed; incorrect
#    or invalid values will be flagged with warnings
#    or errors when radiolog is started

##################################################

# agencyName
# - appears on printed radio log and clue forms
# - default: Search and Rescue
agencyName=Placer County Sheriff's Search and Rescue

# datum
# - valid datums: WGS84, NAD27 CONUS, NAD27 (same as NAD27 CONUS)
# - default: WGS84
datum=WGS84

# coordFormat
# - used for display of all GPS radio coordinates;
#    this setting cannot currently be changed while
#    radiolog is running
# - valid formats: UTM 7x7, UTM 5x5, D.d, DM.m, DMS.s
# - default: UTM 5x5
coordFormat=UTM 7x7

# gisInternalsDir
# - directory containing GISInternals SDKShellb.bat
#    and cs2cs.exe for coordinate conversion
# - if SDKShell.bat is not found at the specified
#    directory, all conversions (UTM, and other datums)
#    will be disabled
# - default: C:\GISInternals
gisInternalsDir=C:\GISInternals

# timeoutMinutes
# - initial timeout interval
# - valid values are 10 minute intervals, from 10 to 120
# - default: 30
timeoutMinutes=60

# firstWorkingDir
# - required first working directory, where all 
#    radiolog data files will be saved
# - radiolog will abort if this directory is not
#    writable
# - default: ~/Documents
firstWorkingDir=~\Documents\sar

# FleetSync List
# - filename of FleetSync lookup of known radios
fsFileName=.\local\radiolog_fleetsync.csv

# secondWorkingDir
# - optional second working directory
# - intended as another form of redundancy and backup
# - all of the same files written to the first working
#    directory will also be written to the second
#    working directory, including rotating backups
# - default: None
#secondWorkingDir=\\192.168.1.50\Radiolog\log

# logo
# - filename of logo to include in printed forms
# - path is relative to ./local
# - default: radiolog_logo.jpg
logo=radiolog_logo.jpg

# clueReport
# - filename of fillable clue report PDF file
# - fillable PDF requirements are described in
#     clueReportFillable_README.txt; the default
#     included file clueReportFillable.pdf already
#     meets these requirements
# - path is relative to radiolog.py
# - default: clueReportFillable.pdf
clueReport=.\local\clueReportFillable.pdf

# server
# - node name of sarsoft server; http get requests will
#    be sent to this server for every incoming set of
#    radio coordinates
# - default: localhost
server=192.168.1.50
`

**Comment by RonRN18** [comment]
> I see the template is no longer included...
> 
> [radiolog.zip](https://github.com/ncssar/radiolog/files/4120282/radiolog.zip)

Just to show how I did things with Placer County, here is what is in my "local" folder. I've added our logo and modified the clueReportFillable.pdf document.


[PlacerSAR.zip](https://github.com/ncssar/radiolog/files/4120285/PlacerSAR.zip)

**Comment by caver456** [comment]
Take a look at #396 - that will address automatic creation of the config file on the first run of radiolog.  Obviously I haven't spent any thought on that in the last many moons, but, it's needed.  As far as documentation, I think the best way will probably be to have the install.md directly link to the default config file which is full of inline documentation and can just be copied and modified as needed.  I'll plan to fix this one up in the next month, thanks for pointing it out.

**Comment by caver456** [comment]
closing, now that #396 is fixed; will add a bit of wording to the docs saying saying that radiolog.cfg has inline docs
