### ISSUE TITLE
Bug: Subject located - no callsign

### ISSUE THREAD

**Issue by polyglot-jones** [ncssar/radiolog#434]
If you hit the Subject Located button [F11] on the new-entry form without first identifying the team, you'll waste your time filling in the subject-lated form. When you finally click OK, it'll complain that the callsign field is required and make you start all over. The subject-located form shouldn't even launch in that case.

**Comment by caver456** [comment]
When hitting F12 with the callsign field blank, these two duplicate lines show up in the transcript:

WARNING Conversion from a typed-in team name () to a formal/extended name failed. Leaving as is.
WARNING Conversion from a typed-in team name () to a formal/extended name failed. Leaving as is.

But that doesn't necessarily cause an issue.

Seems like the thing to do here is disable all quick text buttons and status radio buttons when callsign is blank.
