### ISSUE TITLE
rotate fail due to space in drive name

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#442]
The rotate code doesn't handle a space in the drive name.

(ignore the permission errors - that's a separate issue probably at the OS or network level, and went away on the next session; not sure how we would diagnose that anyway; the drive responded on the windows file navigator, and was not full)

![20200818_174845](https://user-images.githubusercontent.com/18752102/90979337-49921c00-e509-11ea-9cb4-a10c1ea64b5b.jpg)

**Comment by johnpictiin** [comment]
Does this help?

https://support.microsoft.com/en-ca/help/102739/long-filenames-or-paths-with-spaces-require-quotation-marks

**Comment by caver456** [comment]
thanks, no doubt that's the ticket, this one can be at Craig's discretion as far as killing it now or later, since he has a bunch of stuff about to commit and this issue isn't critical.

**Comment by caver456** [comment]
Confirmed (by hardcoding self.firstWorkingDir) this still happens as reported in 2020.

**Comment by caver456** [comment]
Wrapping in quotes in python doesn't solve the issue:

```
195326:Invoking backup rotation script: powershell.exe -ExecutionPolicy Bypass .\rotateCsvBackups.ps1 -filenames  "C:\Users\caver\Documents\Radiolog Space Dir\New_Incident_2022_09_18_195313.csv","C:\Users\caver\Documents\Radiolog Space Dir\New_Incident_2022_09_18_195313_clueLog.csv","C:\Users\caver\Documents\Radiolog Space Dir\New_Incident_2022_09_18_195313_fleetsync.csv"
195326:Accepted2
195326:  writing C:\Users\caver\Documents\Radiolog Space Dir\New_Incident_2022_09_18_195313.csv
195326:  done writing C:\Users\caver\Documents\Radiolog Space Dir\New_Incident_2022_09_18_195313.csv
195326:  writing C:\Users\caver\Documents\Radiolog Space Dir\New_Incident_2022_09_18_195313_clueLog.csv
195326:  done writing C:\Users\caver\Documents\Radiolog Space Dir\New_Incident_2022_09_18_195313_clueLog.csv
Beginning rotation for C:\Users\caver\Documents\Radiolog...
WARNING: C:\Users\caver\Documents\Radiolog could not be found; skipping backup rotation
```

**Comment by caver456** [comment]
This post implied it's just a matter of wrapping in two double quotes.  But, wrapping each string in two double quotes didn't get it either.  Tried wrapping each string in three double quotes and it works.  So - no change to the powershell rotation script - this change is only in radiolog.py.

```
# #442: wrap each filename in quotes, to allow spaces in filenames
#  from https://stackoverflow.com/a/12007707
#  wrapping in one or two sets of double quotes still doesn't work
#   since the quotes are stripped by powershell; wrapping in three
#   double quotes does work:
quotedFilenames=[f'"""{filename}"""' for filename in filenames]
cmd=self.rotateScript+' '+self.rotateDelimiter.join(quotedFilenames)
```
