### ISSUE TITLE
disabled quick text buttons on latest download

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#448]
reported from Yuba County SAR:

I have downloaded radio log on both my laptop and my desktop at work so that I can fleet sync all our SAR radios.  However, the preset selections, such as "at IC, departing IC, starting assignment.... etc, and all the F-key shortcuts are grayed out and do not work.

**Comment by caver456** [comment]
User also confirms that the callsign field is disabled.

![Radio Log 3](https://user-images.githubusercontent.com/18752102/104056595-9cf9c380-51a5-11eb-8837-cdd8ba7d0055.PNG)

**Comment by RadiosPRN** [comment]
Also no longer a problem since rolling back main branch.

**Comment by caver456** [comment]
master branch is fine now, as @RadiosPRN points out.  The issue remains for the master-cj branch which we hope to glean the good stuff from at some point in the future.

**Comment by caver456** [comment]
closing on review, since and future enhancements even if gleaned from master-cj, will need to check to make sure this is not a problem regardless of whether this issue is open or not.
