### ISSUE TITLE
prevent radiolog_rc.txt  from circumventing .gitignore

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#468]
For some reason, even though radiolog_rc.txt is in gitignore, github desktop shows it in the checkbox list of files to commit every time.  Maybe it's because the file is completely rewritten during every radiolog session during shutdown?
This doesn't affect functionality at all, but it would be nice not to need to remember to make sure radiolog_rc.txt is unchecked before every commit from github desktop.
This same behavior shows up on various rc and cfg files in other repos.

**Comment by erinn** [comment]
I suspect this is the reason: https://github.com/desktop/desktop/issues/10379#issuecomment-674014560

**Comment by caver456** [comment]
Good find.  That would be great if thats all it is.  As long as the code
doesn't require the presence of the .rc file (will check tonight if you
don't get to it first) then doing the push with the rc file removed sounds
worth a shot for sure!

**Comment by caver456** [comment]
Looks like the code will raise a blocking messagebox if the rc file is not
found, and after it is closed, will use some hardcoded defaults.  So it
would be safe to just get rid of the file from the repo.  Assuming the
unzip of a fresh download does not nuke out the entire target directory but
instead just overwrites as needed, then the only time someone would see the
messagebox is the first time they ever run radiolog.  At that point, it's
reasonable and intentional to show the messagebox.  Probably overthinking
it, but, do you concur that we should nuke the file from the repo then do
the commit and push?

**Comment by erinn** [comment]
Yeah that seems like it would work and resolve the issue for the future.
