### ISSUE TITLE
Version Number

### ISSUE THREAD

**Issue by erinn** [ncssar/radiolog#472]
As part of the installer work, a version number is needed (unless I missed it somewhere in the code).

You've got a couple of tags in the repo for version 2.0.2 and 2.0.3. That model of version number basically falls under [semantic versioning](https://semver.org) which will work well for this. I'd recommend you pick a suitable number, 3.0.0 or whatever, doesn't really matter and code in a `__version__` variable in your application as well as tagging it upon release (might be a reasonable time to put a 'About' window together that displays the version). 

So this would mean on a new 'release' you bump the version number and git tag before push. Fortunately a lot of developers suffer from having to do this (and forgetting to do this), so there is good tooling for this, one I have used is [bumpver](https://pypi.org/project/bumpver/). But you can use whatever you like, including doing it manually. This will also have the effect of creating [GitHub Releases](https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases) if you like. All of this will be put together in a more automated fashion soonish :). 

So if you're ok with all that, let me know the version number you'd like, I can drop in the code (won't do the about window now)  or you can, and we can push on with the installer work.

**Comment by caver456** [comment]
Sorry for the delay - 3.0.0 sounds grandiose but seems reasonable, if you
can put it in place that would win.  Thanks
