### ISSUE TITLE
coordinate conversion

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#48]
speed up coordinate conversion - uses GISInternals now; maybe pyproj or 'utm'? does pyproj still have external dependency? (degrees to UTM and back; datum can be WGS84 or NAD27)

**Comment by robsheldon** [comment]
If I'm reading pyproj correctly, it's just a Cython wrapper around PROJ.4, which makes PROJ.4 an external dependency. (I think...?)

The "utm" module is really limited and not sufficient.

Maybe https://pypi.python.org/pypi/LatLon ?

**Comment by robsheldon** [comment]
...oh. No. LatLon is just a wrapper around pyproj.

Sigh.

**Comment by robsheldon** [comment]
![image](https://cloud.githubusercontent.com/assets/5345794/21076814/4baa7c24-beea-11e6-9240-8637a21aff55.png)

**Comment by caver456** [comment]
Initially, GISInternals was an external dependency.  Installation was a bit chunky, especially because you need to include the correct share folder (#458).

In an effort to get rid of that external dependency, pyproj was used - but, it's actually just a wrapper around 'proj' which has to be installed from OSGeo4W.  While it provides a bit more consistent python interface, both options are really just using the executable 'cs2cs' that is installed as part of proj.

So, pyproj still has an external dependency.  And, because the system I used for all the development already has proj in place because things like QGIS are installed, that external dependency issue was hidden.  It didn't show up again until the latest radiolog, which uses pyproj instead of GISInternals, was installed on a new computer.

How can this external dependency be simplified or eliminated?  That was the original question in this issue, and it was never really completed.

IN addition, 'pip install pyproj' failed on that new computer with this message - after proj was installed thru OSGeo4W, and after the 'include' folder was added to satisfy the first error (not shown here) about failure to find the default PROJ_INCLDIR folder:

(speculating: maybe this is because the same SHARE folder is missing from the fresh proj installation)

```
PS C:\radiolog-master> pip install pyproj --no-cache-dir
Collecting pyproj
  Downloading pyproj-3.4.0.tar.gz (217 kB)
     ---------------------------------------- 217.3/217.3 kB 4.4 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  Ã— Getting requirements to build wheel did not run successfully.
  â”‚ exit code: 1
  â•°â”€> [23 lines of output]
      PROJ_DIR is set, using existing PROJ installation..

      Traceback (most recent call last):
        File "C:\Users\NCSSAR\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 363, in <module>
          main()
        File "C:\Users\NCSSAR\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\NCSSAR\AppData\Local\Programs\Python\Python39-32\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 130, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\NCSSAR\AppData\Local\Temp\pip-build-env-albio9tq\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\NCSSAR\AppData\Local\Temp\pip-build-env-albio9tq\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\NCSSAR\AppData\Local\Temp\pip-build-env-albio9tq\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 229, in <module>
        File "<string>", line 168, in get_extension_modules
        File "<string>", line 25, in get_proj_version
        File "C:\Users\NCSSAR\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 424, in check_output
          return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
        File "C:\Users\NCSSAR\AppData\Local\Programs\Python\Python39-32\lib\subprocess.py", line 528, in run
          raise CalledProcessError(retcode, process.args,
      subprocess.CalledProcessError: Command 'C:\OSGeo4W\bin\proj' returned non-zero exit status 3221225781.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Ã— Getting requirements to build wheel did not run successfully.
â”‚ exit code: 1
â•°â”€> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
PS C:\radiolog-master>
```

**Comment by caver456** [comment]
Comparing some options, from the top:

- pyproj - requires PROJ executables
- GISInternals (system call to cs2cs from python) - these are the PROJ executables - alternative installation method to OSGeo4W
- [geographicLib](https://geographiclib.sourceforge.io/C++/doc/index.html) - pip installable, but, even in the native C++ docs, it says to use PROJ instead
- GeoConvert - another executable - part of the native geographicLib
- pygeodesy - has potential - looks like it might be a pure-python (no external dependenices) implementation for UTM/latlon >and< datum conversion?  Need to investigate

**Comment by caver456** [comment]
@erinn - do you have any input on this?  How is this handled in the installer?
Right now, it looks like cs2cs.exe (part of PROJ) is the gold standard unless pygeodesy pans out.  Hard to argue with a trusted gold standard, even if it is a relatively ugly external dependency.  But, the installer would need to account for it.

**Comment by erinn** [comment]
The installer can support downloading other packages so it’s a possibility. No idea how it works but we can figure it out. On Sep 13, 2022, at 21:47, Tom Grundy ***@***.***> wrote:﻿
@erinn - do you have any input on this?  How is this handled in the installer?
Right now, it looks like cs2cs.exe (part of PROJ) is the gold standard unless pygeodesy pans out.  Hard to argue with a trusted gold standard, even if it is a relatively ugly external dependency.  But, the installer would need to account for it.

**Comment by caver456** [comment]
Great.  Both GISInternals and OSGeo4W are not exactly what you would call
robust single-click installations - they require some monkey business
afterwards - adding a directory, adding some extra required files, updating
env vars, checking to see if it actually works, etc.  It's not quite clear
which one is easier / more robust.  Like you say, we can look into it
later.  I'll do a full check of pygeodesy first to see if it fits the bill
without the monkey business.

**Comment by caver456** [comment]
To do tomorrow/soon: if pygeodesy seems to work, do a fairly exhaustive test of proj results (cs2cs) vs pygeodesy, across UTM zones etc.  These conversions need to be robust for obvious reasons.

Looks like utm.toUtm8 might fit the bill:
https://mrjean1.github.io/PyGeodesy/docs/pygeodesy.utm-module.html

**Comment by caver456** [comment]
pygeodesy looks viable in the first test.  Converting 39 -120 to UTM is just one meter different in pygeodesy vs cs2cs.  Will use that comparison code to automate some more robust comparisons over a large area.

While the pygeodesy docs do say that it's pure-python, and they spell out the exact dependencies, and it doesn't say there are any dependencies for this type of conversion, and neither PROJ nor cs2cs are listed anywhere, I still want to try it on a system that definitely does not have cs2cs (whether from OSGeo4W or from GISInternals) to be sure.

**Comment by caver456** [comment]
Side note: the long error message from a few comments ago (... non-zero exit status ) appears to be due to failure to run cs2cs.exe from inside a SDK shell.  This code was already in radiolog.  Calling cs2cs.exe without the shell causes the same error as above.  Calling it from within the shell as below resolves the error.  Kind of a moot point since we are working to eliminate calls to cs2cs anyway, so, this is mainly just for reference.

```
cs2csExe=GISInternalsSDKRoot+"\\bin\\proj\\apps\\cs2cs.exe"
sdkShellBat=GISInternalsSDKRoot+"\\SDKShell.bat setenv" # must do 'setenv' as argument, otherwise command will terminate; see SDKShell.bat
...
cmd=sdkShellBat+" & "+cs2csExe+" -f \"%.6f\" "+cs2csArgs # format is not needed for UTM but is needed to return decimal degrees
```
