### ISSUE TITLE
improve methods of specifying operational period

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#483]
Currently, you can click the 'OP 1' button at the top, near the left, to open the 'change operational period' dialog.  This is not obvious.

1) allow user to specify OP number at startup time, probably in the options dialog
2) maybe add some smarts to automatically guess at startup time if this is the next op of an ongoing search; if so (probably needs user confirmation), look at the previous log file, then increment the op for the new radiolog session.

**Comment by caver456** [comment]
partially working in latest commit.  Still to do:

- [ ] remove older duplicate entries from the list of choices
- [ ] create and show the dialog that lets the user choose from previous sessions or to create a new incident

**Comment by caver456** [comment]
Draft of the workflow - open for suggestions:

If there are any sessions from the last n days, this dialog (this is just a draft) will pop up at startup:

![image](https://user-images.githubusercontent.com/18752102/189922710-76e524d0-6223-458c-a2fb-0095023aadb7.png)

The 'YES' button is disabled / grayed out until/unless the user selects a row from the table.

If the user selects YES, the options dialog is not raised afterwards.

If the user selects NO, the options dialog is raised afterwards, where the user can set the incident name.

If there are no sessions from the last n days, the new dialog shown above does not pop up; instead, the options dialog pops up prompting the user for an incident name, as happens currently.

**Comment by caver456** [comment]
@erinn I'll be adding a key to the ini file to accomplish this - probably 'continuedIncidentWindowDays' - an integer as shown in the dialog.  Initial thought is 4; would like to be able to change it from .ini rather than as a hardcode in radiolog.py.  Let me know if this poses a problem since you're working on the options flow.

**Comment by caver456** [comment]
Remaining work after the latest WIP commit: 

 - [ ] print dialog OP choices should reflect the starting OP - right now, 1 is always a choice
 - [ ] reduce number of entries as appropriate (don't show OPs older than the last OP; maybe don't show tiny test files; etc)
 - [ ] adjust height of dialog as appropriate - maybe a fixed height, with scrollbars as needed when there are too many entries
 - [ ] '< 1 day' jumps to '2 days' - seems odd - what about '1 day'? investigate age text calculations
 - [ ] column widths - Incident Name should be wider, OP/Clue narrower
 - [ ] center-justify all columns except Incident Name
 - [ ] header row should be bold on initial display; right now it changes to bold after a row is clicked
 - [ ] make sure cells are not editable by double-clicking etc.
 - [ ] investigate unselection of a row with a second click (which should disable the YES button)
 - [ ] investigate HTML for YES and NO buttons, to make second line smaller font, maybe YES/NO could be bold
 - [ ] initial dialog size - make wider (and fixed size?) to reduce word wrap

**Comment by erinn** [comment]
So one thing that will make life easier for collaboration is if you develop your WIP stuff in a branch instead of master. Otherwise it is a constant moving target, while you are working, that I resync into my fork and then my feature branch. Most folks work with git this way, but I can't of course say it is absolutely correct.

**Comment by caver456** [comment]
Looks like this didn't propagate from email:

Ah, dangit you mentioned that before and I forgot.  Sorry bout that.  Hopefully just one more commit to close out that issue, probably tomorrow.  Would it be better to do that in a branch and PR, or is it too late?  For issues where interim commits aren't necessary, like small bug fixes or small enhancements done in one commit, is it better to still do those in a branch and pull request, or, is direct push to master OK/'safe' in that case?

**Comment by erinn** [comment]
Ah you're in it now, just finish out what you need to. 

Personal opinion, from trying to develop good habits is to always use a branch. It is ridiculously quick to create a branch and then merge it in. I might make personal exceptions for that if I am for instance fixing a typo in a comment or something. 

But too often I am like ok I am going to fix this real quick and then end up down the rabbits hole and five commits later, I've gotten to my destination.

**Comment by caver456** [comment]
Makes sense, I'll try to get in the habit of branch-always, starting after this one is closed out.  Thanks for bearing with my learning curve / cowboy habits.

**Comment by erinn** [comment]
No worries, I'd do the same if I was sole contributor to something for 7 years+

**Comment by caver456** [comment]
Ah, dangit you mentioned that before and I forgot.  Sorry bout that.
Hopefully just one more commit to close out that issue, probably tomorrow.
Would it be better to do that in a branch and PR, or is it too late?  For
issues where interim commits aren't necessary, like small bug fixes or
small enhancements done in one commit, is it better to still do those in a
branch and pull request, or, is direct push to master OK in that case?
