### ISSUE TITLE
handle predefined fleetsync message codes

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#492]
From John P:

My second suggestion is with regard to the fleetsync messaging capabilities. We use Kenwood 3200s and 3220s. They have the capability of selecting canned status messages to send to base or to another radio. What is actually sent is a two digit code in the databurst, each code corresponding to predefined messages. Currently the system just logs the digits. Could this be added so that if RadioLog receives a status message it can pull up the appropriate message and enter it into the log? A use for this might be to have preset messages such as, "Subject deceased" "Request Coroner" "Subject located but nonresponsive" " Multiple subjects deceased" "Send body bag" or other sensitive information. It would allow the field teams to communicate those items without having a voice transmission that might be overheard by family, friends or others eavesdropping.

**Comment by caver456** [comment]
(I had initially sent this response in email - copying it here for completeness)

The fleetsync topic is interesting.  Seems like an obvious relevant capability that needs to be added.  I'll see if we can duplicate that with any of our handhelds - we probably can - in which case I could do the development and testing here.  In the event that I can't duplicate it, can you send me the bits of the transcript that show the incoming fleetsync data string?

Where is the 'decoder ring' defined - how do we know what numbers correspond to what text?  Is that in the hardware and can't be changed?  Or, is it something you set in the kenwood programming program, ending up in the radio's flash memory?  If the latter, what's a robust way of making sure that the radiolog software has the same version of the decoder ring as the radio?  If the radio thinks '01' means 'dead' but radiolog thinks '01' means 'all clear' ...  Can the mobile radio be made to send the corresponding text, instead of the number, over the com port?

**Comment by johnpictin** [comment]
Hi Tom,

The Decoder ring is in programming I think. KAS10 was the Kenwood solution
that mapped status codes to a message.

**Comment by caver456** [comment]
To be clear: can the user (of KAS10, or of the programming program, etc)
define the messages?  Or are they permanently predefined by Kenwood,
universal to all models, and not overridable?  If predefined, then we can
get there from here.  If they can be changed, then we'd need a solid way of
making sure the mobile and the portable are talking about the same thing,
and that could be a good trick to figure out.

**Comment by johnpictin** [comment]
So just to be clear, the status messages sent by the radios are always the
same. What changes is the text assigned to the message.

So it would be necessary to have a customizable lookup table where a canned
message can be selected from. That would allow the greatest flexibility.

But for interoperability, if you consistently use the same teams for mutual
aid and you are on the same system, you would want to agree on some
standard messages.

John

**Comment by caver456** [comment]
Ok thanks for clarifying.

Do you know if the corresponding text is sent as part of the fs data burst,
or, if only the code# is part of the data burst?

If only the code#, then this seems inherently unsafe because it assumes
that the portable and the mobile have the same correspondence tables, which
seems like a bad assumption.  But you say radiolog picks up the code# but
not the corresponding text, so that kind of says the corresponding text is
not sent over the air as part of the data burst.

Does my hesitation make sense?

If a portable sends e.g. '52' because they found a body, but the mobile
decides 52 as 'all good, continuing search', that's a problem.

Can you send me the transcript from the incoming transmission?

Thanks

**Comment by johnpictin** [comment]
The status messages are defined in programming. It is a matter of having a
common set of status messages. The status message can even trigger remote
playback of a precorded sound byte, or be sent in response to a trigger
like fall detection, which is available in some radios. Programmable
buttons on the radio can also trigger messages. The status code received
should be passed through the dataport to RadioLog and not the decoded
message.

**Comment by caver456** [comment]
I'm probably still not understanding the data flow.  To draw a few possible flowcharts, e.g. where '89' is the code and 'all good' is the corresponding plain text:

1. portable (transmitter) does the decoding:
portable user selects '89' --> portable sends 'all good' --> mobile receives 'all good' --> mobile sends 'all good' on USB

or

2. mobile (receiver) does the decoding:
portable sends '89' --> mobile receives '89' --> mobile decodes to 'all good' --> mobile sends 'all good' on USB

or

3. computer does the decoding:
portable sends '89' --> mobile receives '89' --> mobile sends '89' on USB --> downstream software (radiolog) decodes to 'all good'

Sounds like you're saying that #&#8203;3 is what's happening?  How confident are you in that?

#&#8203;1 is the only one that makes sense to me - it's the only one that seems safe / consistent / reliable.  With #&#8203;2 or #&#8203;3, making an assumption that the portable user's intent of '89' matches that of the mobile or of the radiolog correspondence seems unreliable and problematic.  Even if you try to keep those fully locked down and in sync, when another user / agency (e.g. during a mutual aid call) with a different interpretation of '89', or with no decoder ring at all, reads the traffic or sends from their portables, you've got real issues.

Seems like the kenwood folks would know that it's unreliable / unrealistic / unsafe to always universally expect that the mobile - or the downstream application - has been programmed with the same secret decoder ring as the portable, and that they wouldn't want to run the risk of 'air crashes' caused by a mismatched decoder ring.  In other words, in #&#8203;1, seems like the correspondence table would only be referenced by the transmitting radio.

But, I haven't tried, and I'm not sure if our current models have that capability.  The programming program required for the model we use now is fully locked down ($$$ per seat with encrypted passwords - and the data files are encrypted too), and I don't have access to it to try it out right now.  I might be able to get access to do that in the near future.  If you could send the radiolog transcript file during a status code transmission, that would help.

If it's #&#8203;2, that seems dodgy to me, but by the time radiolog receives it, plain text is plain text, and adding the capability to radiolog to show it as a received decoded message wouldn't add any further dodginess.

But, honestly, if it's #&#8203;3, I wouldn't plan on adding that feature to radiolog for all the reasons above.  Wouldn't want to be the wobbly link in that chain.  Unless there's still something I'm missing?

**Comment by johnpictin** [comment]
I will verify and get back to you. I have only limited experience with it
myself. I know the current send message from base to handheld or mobile
works well.

John

**Comment by caver456** [comment]
Hi @johnpictin just checking to see if you still want to pursue this issue, based on the concerns above?

>> But, honestly, if it's #​3 [computer does the decoding: portable sends '89' --> mobile receives '89' --> mobile sends '89' on USB --> downstream software (radiolog) decodes to 'all good'], I wouldn't plan on adding that feature to radiolog for all the reasons above. Wouldn't want to be the wobbly link in that chain. Unless there's still something I'm missing?

If '89' is the only thing that would be going over the airwaves, then I think it's safer (and more accountable) to get humans to decode it in real time, rather than assuming the decoder correlation files are the same and are up to date.  If that was the plan, let me know and I'll close this issue.  Thanks

**Comment by johnpictin** [comment]
Hi Tom,

Sorry that I haven't been in touch on this. To be honest I have been too
busy to test it out. I do appreciate your logical reasoning. Let's close
it for now .Once I find out exactly how it works we can always resurrect
the idea later if it was of value.

I'm fortunate in that the teams that we mostly work with in mutual aid are
utilizing mostly Kenwood radios and that we manage the programming for
these teams as a collective to ensure that it is consistent. If our Radio
Shop makes a change for one team, all teams will eventually get it. We make
sure that there is authoritative copy of what the programming needs to
include.

John

**Comment by caver456** [comment]
Thanks, closing for now.  It's definitely a good thing that all your
regional teams are coordinated like that - that's certainly not true
everywhere!
