### ISSUE TITLE
automatically send transcripts on clean shutdown or crash or traceback

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#507]
Brainstorming.  It would be good to get the log files to the developer ASAP in each of these cases.  Generate an email and queue it to send the next time internet is available, which will likely be most of the time due to starlink etc.  Need to make sure this doesn't interfere with radiolog operation, bandwidth, etc - make sure this is not a source of lag, and, don't send more frequently than necessary.

**Comment by johnpictin** [comment]
Just curious on this, do the logfiles include the text entries from the
NED? If so this would create a privacy issue under Federal and Provincial
laws for Canadian users. The text and possibly coordinates would need to be
obfuscated or redacted. Sorry to be a pain in the butt. I do agree that it
needs to be intact as far as local logfiles are concerned, but data being
automatically sent would need to be scrubbed.

Maybe sending logfiles could be an option in the config that could be
enabled or disabled?

Speaking of logfiles, an automatic rollover on startup with a date and
timestamp in the filename would be helpful. I checked on my logfile and it
was 1.5Gb. it's a lot of text to wade through. Just a thought.

John

**Comment by caver456** [comment]
Definitely a good point.  Was wondering about that, but, hadn't thought of the obfuscation idea.  The goal is to facilitate debug, so obfuscated message bodies and coordinates shouldn't prevent the ability to reproduce the bug, except in some rare oddball cases.

And/or automatically sending to a secured location which the developer can get to separately.  Python can do https, smtp, signed requests, or whatever is needed, but keeping it simple / not jumping through too many hoops is important: if enabling this automatic delivery becomes more complicated than going to the dispatch computer with a thumb drive (i.e. as a 'trusted' person), then it probably wouldn't get much traction.

**Comment by caver456** [comment]
After some thought, closing this as 'wontfix' - it's outside the scope of what the radiolog program should do.  The transcript gets saved, so, what happens with it from there is up to the user / local admin.  As @johnpictin pointed out this also reduces / avoids privacy concerns.
