### ISSUE TITLE
checkForContinuedIncident possible bug

### ISSUE THREAD

**Issue by erinn** [ncssar/radiolog#518]
I believe this should be `self.continuedIncidentWindowDays` otherwise you are hardcoding the value and the settings becomes worthless I believe. 

https://github.com/ncssar/radiolog/blob/5ad5862416afe6fb47cab0e8555342d1a0b09172/radiolog.py#L975

**Comment by caver456** [comment]
Good catch, thanks, right you are.  If you don't get it first, then, I'll
incorporate in one of the enhancements I plan to do before the release
regarding improvements to the continuedIncidentDialog.
