### ISSUE TITLE
review 'continue time' functionality

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#538]
Right now, incoming transmission resets lastModSec, even if nothing was typed.

Is this appropriate?  If so, do we want to reset on BOT or EOT or both?  If it's a long transmission, you could possibly go through the entire continueSec between BOT and EOT.

(This was tested with a stopwatch and fsTester.)

**Comment by caver456** [comment]
Also: new stack entries show up for repeated calls from the same team show up when a clue dialog is open (for a different team?).  Looks like a side effect of disabling timers for all teams when one team has a (clue/subject/CCD) dialog open?  Need to do more work to reproduce.

**Comment by caver456** [comment]
Did some more testing - still couldn't reproduce the issue of multiple stack tabs per callsign during a continued conversation.  Closing this issue for now.

**Comment by johnpictin** [comment]
Hi Tom,

I did have this issue on one of earlier builds. I don't exactly remember,
but I think it resolved itself by upgrading to the next current version. I
would have also swapped the USB ports to force the com port driver's to
reload.

Sorry that I can't be more helpful.

John
Castlegar SAR

John
