### ISSUE TITLE
add support for new locator method Nov. 2022

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#576]
The Locator Group technique is deprecated.  The new technique [documented here](https://training.caltopo.com/all_users/share/live-tracking#livetracks) uses one LiveTrack feature per device.

![image](https://user-images.githubusercontent.com/18752102/200081314-7644fdaf-7172-47ed-97a3-a345ca67297a.png)

Looks like it will have some big advantages:
- no more need to add a Locator Group - no need for the map creator to add any feature(s) in order for locators to just show up, assuming radiolog can add the new LiveTrack per callsign from code
- automatically stops listening 24hr after the last update for each locator
- the locator is specific to a certain map - the previous technique caused locators to appear on all team maps

Considerations:
- make sure radiolog works for old-style (Locator Group) as well as new-style (LiveTrack) since we can't be sure what version of CTD is installed
- make sure this works on the latest CTD
- see if it works on sartopo.com
- should radiolog try to send request to multiple mapIDs with each update?  One for CTD, one for sartopo.com - others?  One for localhost?  Mutliple mapIDs per host?

For discussion:

- 'old' locators = the deprecated LocatorGroup method
- 'new' locators = the new LiveTrack method

** Note that 'Shared Locations' overlay (checkbox) layer must be on in order to view locators on the map!  This is a new requirement sometime in the last year or so.  The dropdown by the Shared Locations overlay needs to be set to 'All' or 'Local Stations'.  These radio reports are only showing up as Local Stations, and not as NCSSAR.  This is either because the callsigns being sent from radiolog don't match the callsigns set as Trackable Devices in the team account, or, because fleet locators are a separate thing from Trackable Devices. 

Note that the 'while offline' checks below might be irrelevant since the testing computer was not disconnected until after it had already been connected, and it may have cached the list of Trackable Devices when connected.  A complete test, if necessary, would mean adding a device to the list of Trackable Devices >after< the testing computer is disconnected from the internet. 

- [x] confirm old locators on CTD 4228 (8/11/22)
  - [x] while online: ID that has been added as Trackable Device
  - [x] while online: ID that has NOT been added as Trackable Device
  - [x] while offline: ID that has been added as Trackable Device (as of the last time it was online)
  - [x] while offline: ID that has NOT been added as Trackable Device (as of the last time it was online)
- [x] confirm old locators on CTD 4230
  - [x] while online: ID that has been added as Trackable Device
  - [x] while online: ID that has NOT been added as Trackable Device
  - [x] while offline: ID that has been added as Trackable Device (as of the last time it was online)
  - [x] while offline: ID that has NOT been added as Trackable Device (as of the last time it was online)

NOTE: sending locator updates to sartopo.com (online) from radiolog will definitely not work with the current (Nov 11 2022) radiolog code.  Radiolog is currently hardcoded to send to port 8080 regardless of URL - and the URL is probably different anyway - it could even require signed requests, available in sartopo_python.  While it might be an interesting feature request to send the Locator Group requests to sartopo.com, it's probably not relevant to this issue.

Also note that the Add --> Locator --> Live Track - Fleet, Email, Other dialog says you CAN send to caltopo.com - hopefully without the need for a signed request.   So that's something to try with the Live Track requests going forward.

- N/A:  confirm old locators on sartopo.com
  - N/A:  while online: ID that has been added as Trackable Device
  - N/A:  while online: ID that has NOT been added as Trackable Device

**Comment by johnpictin** [comment]
From what I understood one can configure all of their devices to be on the
shared location layer. This will also include team members sharing
locations from their personal phone and the caltopo app.

Then, when in your map, you can go to the layers window, under Realtime
Data, turn on the Shared Locations layer and all of your team devices will
appear. You just select the ones you want to include in your map and "Start
Recording" for those devices. The listeners only have to be created once
that way.

Feel free to correct me if I'm wrong. It's happened before.

John Pictin
Castlegar Search and Rescue

**Comment by johnpictin** [comment]
Further to my previous mail, RadioLog should just send the request and not
specify the map. On each map you choose which devices to track from the
Shared Locations layer. I hope that makes sense.

John

**Comment by caver456** [comment]
Thanks for the info, I haven't tried out the recent shared locations
functionality, but will be doing so soon - and then figuring out how
incoming fleetsync GPS coordinates, passed along thru radiolog, fit into
the overall shared locations picture.

**Comment by caver456** [comment]
Tried to get the first items on the checklist, but, not seeing the locator show up as expected.  At this early stage of testing, and having not looked at locators in detail for a while, gotta assume it's something I'm doing wrong - but the log4j lines seem to not be working, see https://help.caltopo.com/hc/en-us/requests/19012

**Comment by caver456** [comment]
Got past the log4j issues and such based on caltopo help threads.  Basically you need to turn on the 'Shared Locations' overlay / checkbox layer.  Also noted at the top of this issue:

 ** Note that 'Shared Locations' overlay (checkbox) layer must be on in order to view locators on the map! This is a new requirement sometime in the last year or so. The dropdown by the Shared Locations overlay needs to be set to 'All' or 'Local Stations'. These radio reports are only showing up as Local Stations, and not as NCSSAR. This is either because the callsigns being sent from radiolog don't match the callsigns set as Trackable Devices in the team account, or, because fleet locators are a separate thing from Trackable Devices.

**Comment by caver456** [comment]
Finished confirming the Locator Group ("LG") style of requests work with 4228 and 4230, though they display as Shared Location dots - not as actual map features in the left bar.  Moving forward to the Live Track ("LT") style:

No luck sending several different request from postman (after having confirmed that sending the LG-style request from postman works as expected).  Here's what I tried so far:

1) in CTD: Add --> Locator --> Live Track - Fleet, Email, Other - Callsign = 100
2) tried all of these requests to localhost:8080 - they all return 200, but no response body:
- http://localhost:8080/api/v1/position/report/100?id=3031&lat=39&lng=-120
- http://localhost:8080/api/v1/position/report?id=FLEET:100-3031&lat=39&lng=-120
- ... there are MANY more to list; rather than listing them all here, will just open a caltopo help ticket.  BUT it kind of looks like CTD just doesn't listen for LT-style requests which would be a bummer - it kind of looks like you have to send them to caltopo.com and then they get pushed out to whoever is looking at the map.

Rather than adding one map feature per fleet, it looks like we need to add one map feature per callsign?  The following shows a black dot at the correct location (when running CTD and viewing a synced map) - and it also looks like a requirement is that the admin has added 100-3035 as a trackable device?

1) in CTD: Add --> Locator --> Live Track - Fleet, Email, Other - callsign = 100-3035, label = bbb
2) send a GET request to https://caltopo.com/api/v1/position/report/100?id=3035&lat=39&lng=-120

The black dot shows fairly quickly, but, clicking 'bbb' in the left bar doesn't zoom to it - it shows an alert saying 'bbb has no location information'.

After a few minutes and panning the map, that black dot changes to a red dot with label 'SAR 35' which is what the admin had entered as a trackable device.  After it changed to a red dot, clicking 'bbb' in the left bar shows the same alert as above.

So: turning all of this into a hopefully logical help ticket for sartopo:
- Does CTD listen for Live Track http request updates, or, do they have to go to caltopo.com and then get pushed out to the synced map?  In other words, can Live Tracks be used with CTD without internet connection?
- Can Live Track be used to add just one map feature that listens for any callsigns in a given fleet number, in the same manner as a Locator Group?  Or, is it strictly necessary to add a new Live Track feature for every expected callsign?
- Does each callsign (fleet number - device ID pair) need to be added as a Trackable Device by the team account administrator, in order to get updated locations pushed out to CTD viewing a synced map?  Or, is there a way for the admin to specify that all devices in a given fleet should qualify as Trackable Devices?
- it looks like the label and color specified in the Live Track feature in the left bar do not get applied to the actual Live Track dot, and that no line is showing up as the locator gets new updates, even though 'stop recording' shows in the Live Track edit dialog.  These facts implied that the Live Track feature was not actually getting used for anything, and that maybe the updates are coming in via the Shared Locations' overlay instead.  That does appear to b the case: if you then uncheck 'Shared Locations', the dot that showed up after the request to caltopo.com goes away; turning on 'Shared Locations' again shows the dot again.  [possible bug in here: I had 'shared locations' on and set to 'All'.  I then changed it to NCSSAR (our team account) and the dot still showed.  Makes sense.  Then I changed to 'Local Stations' and the dot still shows.... seems odd.  Then I change to 'Nevada County' - a different subteam - and the dot disappears, as expected.  Then I change back to 'Local Stations' and the dot does not appear.  That's as-expected but looks like the transition is a bit out of whack.  Then I change back to NCSSAR and it shows again.  So maybe changing to 'Local Stations' is just not hiding things that are not actually Local Stations?]
- will the Locator Group method be going away anytime soon?

**Comment by caver456** [comment]
This issue is on hold for a bit, pending the caltopo help ticket as a above, https://help.caltopo.com/hc/en-us/requests/19050 and generally until we have a good understanding of the current locator situation and of the way forward.

We did confirm last night in the IC trailer (CTD 4230) that LG-style locators are still working (with the new-style display requirement that Shared Locations must be on).

**Comment by caver456** [comment]
@RonRN18 @johnpictin @RadiosPRN @erinn and please send a link here to any other users that use fleetsync radio locators: the caltopo help thread has concluded; I talked some with the caltopo CEO too; other issues have been finished up and a few more are still in progress; so, it's about time to resume work on this issue.

It would be good to get other users' input first.  We did a quick survey of command post users on our team - there were just a few responses, which is a good data point that says that not many people make a lot of use of these locators, especially in places with good cell coverage where apptracks are sufficient, but, I think we knew that.

If you have a few minutes, please fill out this very short survey on the topic, and note what agency you're with in the name field:

https://forms.gle/LSoY6AMwsAbdqQyAA

I feel like the right way forward here is to make radiolog capable of being the entire 'radio locator management' solution.  Maybe there's an options checkbox to enable or disable this type of management.  I can spell out the list of features we'd want to add, but at this point it be great to hear some other thoughts and ideas on it.

This would be kind of a large undertaking, mainly because nothing in radiolog yet makes use of sartopo_python.  We'd need to have radiolog create a link with a CTD map (it should work with a sartopo.com map too).  The functionality to add or modify markers, put them in folders, etc etc is already pretty well in hand in sartopo_python and other NCSSAR projects that use it (plans console; sartopo_address; assignment tracker; probably some others).  So, if anyone thinks this is misguided, now would be the time to chime in so we can reconsider the priorities.  Thanks

**Comment by johnpictin** [comment]
Speaking for our team, we make regular use of the locators. The functions
that currently are in RadioLog, using the locator group function object in
SARTopo has been sufficient.

I did peek around at some of the other projects that you have on the go,
but I wasn't sure how they fit into the puzzle.

We have 3 additional teams nearby that are at various stages of deployment
of RadioLog and will rely on locators with Kenwood Radios.


John

**Comment by caver456** [comment]
Thanks to those that chimed in.  Got some good useful feedback from the survey response wording.

So - a few decisions:

- add capability for radiolog to be the full 'radio locator management solution'
- in addition, continue to send the old-style requests that worked with LocatorGroup, since those requests continue to work with Shared Locations
- allow the user to turn this management on or off per session, with a default set in the local config file; the management should be On by global default (i.e. if it's not specified in local config file) - subject to change based on feedback
- close this issue due to too much back story, and make a new issue to capture the work going forward
