### ISSUE TITLE
operator login

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#579]
From a request 11/17/22:

could there be a login dialog that as the comms operator changes, the new person, even if for a short time, pee break, etc, could type in their ID or name (during MAs non-NCSSAR would enter?) Creating an entry or tagging each message.

**Comment by caver456** [comment]
There are two distinct parts to this task:
- [ ] GUI - portrait silouette with initials / ID at the top right; just click that icon to show a dialog to change the operator; allow a cyclic field of known operators, but also allow first-time operator name / ID entry
- [ ] generated PDFs - just showing the operator change as another entry would be easy to miss; find a more prominent way to show who was the operator for each call.  Maybe a header entry, 'Operator(s) on this page:' then if more than one operator is listed, this would serve as the queue to look through the entries for 'OPERATOR CHANGED' or such.  Or, maybe a grouping-bracket-line on either the left or right margin, showing operator initials / ID.

**Comment by caver456** [comment]
options for indicating operator(s) on PDF - in addition to the fact that each operator change is an actual log entry:

1. add the name and ID of the currently-logged-in operator somewhere in the header (on the MESSAGE column header?)
2. add the list of operators on this page somewhere in the header
3. add a column to indicate operator at the time of each entry
4. add a bracket or vertical line to the left of the table 
5. make entries that indicate operator change visually stand out (bold, or thick border, or gray background, etc), and apply to all teams (for team logs)

**Comment by caver456** [comment]
5. is pretty easy, by adding a new style, with 'Normal' as the parent, and just changing the necessary attribute(s):


```
	styles = getSampleStyleSheet()
	styles.add(ParagraphStyle(
		name='operator',
		parent=styles['Normal'],
		backColor='lightgrey'
		))
```
...
while iterating over rows:

```
		style=styles['Normal']
		if 'RADIO OPERATOR LOGGED IN' in row[3]:
			style=styles['operator']
	        radioLogPrint.append([row[0],row[1],row[2],Paragraph(row[3],style),Paragraph(row[4],styles['Normal']),Paragraph(row[5],styles['Normal'])])
```

![image](https://user-images.githubusercontent.com/18752102/209853767-589f7ac4-8a29-4b53-921d-70122c50b34f.png)

But - 5 is not a complete solution on its own.  Still need to pursue one or more of the other options.

**Comment by caver456** [comment]
Most of the other options can't be easily done with reportlab.  The table split doesn't have a concept of the first entry row number of each page.  Even if it did, changing the header row per page, to name the operator at the start of the page, would be pretty tricky if even possible.

So, it looks like making a note of the operator initials on every row is the way to go.  For option 3, adding a new column will take up space on every row; instead, look for cells that aren't usually filled up, for a space to insert the operator initials for that row.  Seems like the best choice is at the start of the message cell.

The row header could be changed to '[Operator Initials] MESSAGE' and each cell could look like '[ZZ] STARTING ASSIGNMENT'.  This will probably be a bit confusing for anyone reading the paper log later.  Is there a cleaner way?

**Comment by caver456** [comment]
Plan B: don't do any other options - call it good with just option 5 (gray lines) as above.  This means that anyone wanting to see who was logged in for a given line might have to flip backwards a page or two.  But, this is probably rare and maybe just fine as long as the LOGGED IN lines are prominent enough.  Time to ponder... will do a commit with option 5 and nothing else, for the moment.

**Comment by RadiosPRN** [comment]
Just my opinion - we don't typically need to know this information so option 5 as you currently have it should be good for us. It's in the log if needed but doesn't take up much real estate. You can always flip back and check if necessary.

**Comment by caver456** [comment]
Thanks - I thought the whole login thing was a pretty obscure request that would be VERY rarely used.  That's probably true.  But, having some easy form of accountability, and especially knowing who typed in the clue wording to be able to ask them later (in addition to asking the team), does make sense, as long as it stays lightweight.  Latest thought: operator initials in square brackets at the end of the message, instead of the beginning of the message.  Looking through some generated PDFs, it would be >very< rare that appending [JD] or such would cause a new wrapped row, and even if it does, that's not actually a problem.  This would be way less confusing than having the [JD] at the start of the message body cell.  Plus, it would be easy to propagate to team logs and to clue reports.

**Comment by caver456** [comment]
Hmmm.... easy to accomplish, but, still causes confusion.  In this case, what's the name of the assignment that team 1 is starting?  This kind of says a very small separate column may be best.
![image](https://user-images.githubusercontent.com/18752102/209862672-2c402895-98a6-450d-acdc-3086be3797f5.png)

**Comment by caver456** [comment]
Latest thought: add another column after MESSAGE.  The header can be a very small silhouette icon without text.

The config file, read at the start of the session, can be used to disable all the login functionality.  There's no need for an option to toggle visibility of that column within a session.

Hopefully, the only thing needed to control column visibility during __init__ is something like

```
if not self.useOperatorLogin:
   self.ui.tableView.hideColumn(4) # or whatever column number it happens to be
```

The bigger change would be that self.radioLog should now have an additional element.  This might be impactful, but hopefully not too bad.  For that reason, it's probably better to work no the other parts of this issue first (usage, GUI cleanup, config setting to completely disable login, etc), and leave the data structure change for last.

**Comment by johnpictin** [comment]
What about doing a manual FROM entry with the team being Operator or Comms
and type in a comment Operator change New operator: Joe Blow.

When the operator returns do a manual From and repeat the entry entering
the new name.

If you want to get fancy, give it a hotkey (Ctrl+o ??) that calls the From
entry, assigns the default team (Comms or Operator), enters the default
message and waits for the name or ID to be input. Make that entry bold,
italic, different font or a different style combination, and it will stand
out on the page.

This will create a tab in the teamlist that will have all of the operator
information set apart for the operational period.

A button could be tucked somewhere that executes the hotkey sequence for
those that don't want to remember the keystroke, prefer a mouse or use a
touchscreen.

It's just an idea that might have a simpler development curve and still get
an adequate result.

John

**Comment by johnpictin** [comment]
A little further to my previous suggestion, have a default Operator or
Comms team tab created by default at the start of the task. Right clicking
on this tab will have the option of New Operator. Having this tab will also
let you assign a handheld radio to this tab in case the operator leaves the
desk with a portable or someone from the ICP is sent out to be a human
repeater. Then Comms can be assigned as the Relay Team.

I Think I need to stop thinking.

John

**Comment by caver456** [comment]
Thanks for the brainstorming John.  To maybe address some of what you're thinking about, here's a pic of the login dialog that comes up when you click the silhouette at the top right, and also comes up at startup:

![image](https://user-images.githubusercontent.com/18752102/209955556-979d626c-ab92-4f87-895b-617fecdab670.png)

It does create an automatic entry with the incoming operator's name and ID when you click 'Log In'.  The checklist a few comments back (which I keep editing to add more items) shows the game plan and details.

I'd rather keep going with this silhouette-and-dialog-and-added-column route than take up valuable real estate in the team tabs bar. (Still need to figure out a way to display tons of team tabs which definitely does happen on big searches - but that's a separate issue.) 

Adding another team tab that's not really a team would have some other complications too.  

Regardless - brainstorming is definitely appreciated!

**Comment by caver456** [comment]
Almost all other checkboxes are checked - starting work on the data structure and column displays now.

**Comment by caver456** [comment]
Known issues with the added column display:
- It would be nice to find a way to center the header pixmap horizontally within the header, but, this doesn't seem to be straightforward.
- team tables don't appropriately size columns until fontsChanged.  This is very apparent on the operator initials column, but, affects all columns and has probably been the case for a long time.  Opening a new issue - won't try to solve it here.

**Comment by caver456** [comment]
All done.  A few things could be cleaned up in the future, but all the functionality is there.
