### ISSUE TITLE
add NXDN support (Kenwood NEXEDGE)

### ISSUE THREAD

**Issue by caver456** [ncssar/radiolog#628]
One zone on NCSSAR radios now does digital (NEXEDGE, which is Kenwood's implementation of the NXDN 'standard').  As far as we can tell from various docs and comments, Fleetsync is distinct from NXDN: FleetSync is over analog, and NXDN is over digital.  Interesting that the KPG-D1N System page shows both FleetSync and NXDN on the same page, if you select NXDN as the system type.  That is probably done to accommodate the ability to send GPS data on the Data Zone-Channel (where the radio changes the channel briefly to send data on a different dedicated channel, then changes back to the selected channel afterwards), which could be analog using Fleetsync.  It's all pretty confusing - our understanding of it will probably improve if/when we go farther down the rabbit hole. 

Fleetsync still works fine for most zones, so, this is not a top priority.

We want to add the same functionality as Fleetsync:

- [x] update fsTester
- [x] read CID data
  - [x] spawn NED with correct callsign
  - [x] spawn CCD if needed
  - [x] expand 'elif uid' clause at end of fsParse, to do the same things as the 'if fleet and dev' clause
    - [x] update the fs log (or equivalent) - includes passive mic bump filtering
    - [x] allow for filtering of certain uid's, in the same manner as selective fs filtering
- [x] read GPS data
- [x] send text message
  - [x] send to single NXDN device
  - [x] send to team of multiple specific NXDN devices
  - [x] send to team of both NXDN and FS devices
  - [x] NXDN broadcast
  - [x] Full broadcast (NXDN and FleetSync)
- [x] poll for location 

And some tasks to consider for interaction between FleetSync and NEXEDGE:

- [ ] consider treating NEXEDGE CIDs the same as their FS counterparts (should 01001 automatically get the same callsign as 100:1001?)
- [ ] consider adding a note in NED and/or the actual radiolog entry when a call came in over NEXEDGE

Logistics:

- [x] merge 3.7.0 into this branch
- [x] cleanup after merge commit to make sure intended NXDN features are still present
- [x] confirm that features and bug fixes since 3.5.0 still work, since conflicts had to be resolved in radiolog.py, centering around fsLogUpdate and getCallsign
  - [x] #619 
  - [x] #640 
  - ~~#623~~ skipping verification since code is in place and large test case is no longer available
  - [x] #637 
  - [x] #614 
  - [x] #624 
  - [x] #615 
  - [x] #638 
  - [x] #642 
  - [x] #643 
  - [x] #655 
  - [x] #452 
  - [x] #650 
  - [x] #651 
  - [x] #653 
  - [x] #630 
  - [x] #636 

QA before merging into master:

- [x] FS call-in, no GPS fix - pops up CCD as needed and NED
- [x] repeated calls from above - should respect continue-time and not pop up additional NED
- [x] repeated calls from above just after the continue time - should pop up additional NED
- [x] repeat all above with GPS fix - make sure NED(s) show coords
- [x] multiple fs radios - make sure CCDs and NED stacks etc are as-expected
- [ ] mix NX call-ins with FS call-ins
- [x] send text to FS (single)
- [x] send text to FS (multiple)
- [x] GPS poll to FS
- [x] broadcast - check on FS radios as well as NX radios - should only receive the text once per radio
- [ ] consider re-checking previous fixes again, listed in 'logistics' above
- [x] consider re-checking all expected NX functionality before final merge

**Comment by caver456** [comment]
Not able to figure out just yet how to get NXDN GPS data to show up in radiolog.  Just CID on both BOT and EOT.

Confirmed that the portable used for testing is sending analog Fleetsync GPS data on the digital channel if it was contacted using analog within the last ten seconds, but not if the previous transmission was digital.  (Ken has details if needed).  Still working on it...

**Comment by johnpictin** [comment]
This will be really helpful as we then could integrate Icom radios along
side the Kenwoods. It would just be a matter of configuring the strings
that the Icoms transmit.

John

**Comment by caver456** [comment]
John, can you send some of the icom strings, ideally as utf8-decoded 'text' (with the smileys and hearts) but hex or binary or whatever other format might be fine too?  Since I don't have an icom radio set to test with, that would probably be a legth back-and-forth process.  Adding it as a checkbox category here, since icom is different than NEXEDGE (Kenwood's implementation of NXDN).

**Comment by caver456** [comment]
On second thought - probably best to make the Icom NXDN support into a separate issue, since this issue will hopefully be resolved and closed sooner than Icom.

**Comment by johnpictin** [comment]
Have the portable and the base both been programmed with equivelant NXDN
and Fleetsync settings? I'm not exactly sure how it works, but from the
reading I was doing NXDN does support Fleetsync type I AND II calls.

This is done so that a site that is already running Fleetsync
mobile/handheld radios can migrate into an NXDN setup. They won't lose
comms as the digital radios can run dual mode by embedding the digital
signal into the analog audio until they go full digital only.

When adding radios into the table in programming.  You can copy Fleetsync
IDs to NXDN but not NXDN to Fleetsync. NXDN ID's have a different format.

i wish I had the software and cables to work with you on this.

John

**Comment by caver456** [comment]
Thanks for the leads - I thought they had been set correctly but clearly
they have not.  I don't have the setup here at home - am planning to spend
some more quality time at the station with KPG-D1N and the docs and the
mobile and portable radios sometime soon.

FS CID and GPS are getting through on the channel that has NXDN enabled,
so, the FS settings are probably good, but not so much for the NXDN
settings.

**Comment by caver456** [comment]
Was able to get GPS over NXDN working.  We just some bad settings in the portable radio.  The full transmission looks like this - note that the GPS data came in on BOT, immediately after CID - since there is no BOT/EOT distinction in the NXDN portion of the Kenwood programming software:

```
102917:     DATA IS WAITING!!!
102917:      but not valid fleetsync data.  Scan continues...
102917:☻gI1U03001U03001♥☻$PKNDS,182916,A,3912.3127,N,12104.5647,W,,,,,00,U03001,207,00,*59
$PKNSH,3912.3127,N,12104.5647,W,182916,A,U03001,*4C
$GPRMC,182916,A,3912.3127,N,12104.5647,W,,,,,*02
$GPGGA,182916,3912.3127,N,12104.5647,W,1,,,,,,,,*43
♥
102918:     DATA IS WAITING!!!
102918:      but not valid fleetsync data.  Scan continues...
102918:☻gI0U03001U03001♥
```

**Comment by dBitech** [comment]
This is my NXDN setup using a fairly trivial serial port reader, and modified pynmea2 to provide the GPS position decoding of the $PKNDS sentence ![image](https://user-images.githubusercontent.com/10306894/218343114-d3ef6c6c-0895-425c-9568-5fe6dc3aa750.png)

**Comment by caver456** [comment]
Just did the first commit and pull request.  Will try to keep comments and discussion on the pull request from here on out.

**Comment by caver456** [comment]
Disregard the last - re-re-re-thinking, there's too much discussion on the issue thread before the pull request even exists, so, probably best to keep the discussion on the issue page rather than the pull request page.
Anyway - will expand the checkbox list at the top of the issue to include details.

**Comment by caver456** [comment]
Fiddled around with radtext and realterm today, to reverse-engineer the outgoing data for poll and text, in the same manner as was done for fleetsync.  Review #18 for lots of good background info on getting realterm to work with radtext or radiolog; additional notes from an email to self:

- make sure a virtual com port bridge is running com1 <--> com2
- run fsTester which will grab and lock com1 by default
- run realterm on com2: 9600 8N2,Change, Open
- display mode ASCII should be sufficient
- send data with fsTester and watch it show up in RealTerm

now to duplicate this flow from radtext:

- close fsTester if it was running, to free com1
- run radtext server on com1: 9600 8N2
- make sure the radio you want to mimic sending to is in the radio list (note, the radio list editor gui doesn't seem to save the file - maybe that's a restriction of the demo version - so you need to see what changes to make using the radio list gui, then hand-edit the file accordingly - keep in mind only the first three are usable / will appear in the main gui with the demo version)
- in the main gui radio list in the left panel, right-click the radio in question and click to send the data you want to send
- you may need to click the bottom-right colored square to change it from yellow to green, and then wait 5-10 seconds for the data to actually get sent.  Not sure why this is.

Added some notes to radiolog.py with the reverse-engineered outgoing data for poll and text over nexedge, copied here.  Need to test next time at the station.

Also, not quite sure yet about nexedge broadcast: might need to program each radio to have the same group id, if they are not already programmed that way.


```
	# Serial data format for sendText and pollGPS functions was discovered by using RADtext 
	#    https://radtext.morganized.com/radtext
	#  along with a virtual COM port bridge, and a COM port terminal emulator to watch the traffic

	# sendText - outgoing serial port data format:
	#
	# <start><length_code><fleet><device><msg><sequence><end>
	#
	# <start> - 02 hex (ascii smiley face)
	#   for NEXEDGE, insert 67 hex (lowecase g) after 02
	# <length_code> - indicates max possible message length, though the plain text message is not padded to that length
	#   46 hex (ascii F) - corresponds to 'S' (Short - 48 characters)
	#   47 hex (ascii G) - corresponds to both 'L' (Long - 1024 characters) and 'X' (Extra-long - 4096 characters)
	#   if you send COM port data with message body longer than that limit, the mobile will not transmit
	# <id>
	#   FleetSync: <fleet><dev> - plain-text three-digit fleet ID and four-digit device ID (0000000 for broadcast)
	#   NEXEDGE: U<uid> - U followed by five-digit unit ID
	# <msg> - plain-text message
	# UNUSED: <sequence> - plain-text two-digit decimal sequence identifier - increments with each send - probably not relevant
	#   NOTE: sequnce is generated by radtext, but, it shows up as part of the message body on the
	#          receiving device, which is probably not useful.  Interesting point that we could
	#          add timestamp or such to the message body if needed, but, this is not a separate token.
	# <end> - 03 hex (ascii heart)
	#
	# examples:
	# FleetSync:
	#  broadcast 'test' (short):  02 46 30 30 30 30 30 30 30 74 65 73 74 32 39 03   F0000000test28  (sequence=28)
	#  100:1002 'test' (short):  02 46 31 30 30 31 30 30 32 74 65 73 74 33 31 03   F1001002test31  (sequence=31)
	# NEXEDGE:
	#  03001 'test' (short):  02 67 46 55 30 33 30 30 31 74 65 73 74 31 31 03   gFU03001test10  (sequence=10)

```

```
	# pollGPS - outgoing serial port data format:
	#
	# <start><poll_code><fleet><device><sequence><end>
	#
	# <start> - 02 hex (ascii smiley face)
	#   for NEXEDGE, insert 67 hex (lowecase g) after 02
	# <poll_code>
	#   52 33 hex (ascii R3)
	# <id>
	#   FleetSync: <fleet><dev> - plain-text three-digit fleet ID and four-digit device ID (0000000 for broadcast)
	#   NEXEDGE: U<uid> - U followed by five-digit unit ID
	# UNUSED - see sendText notes - <sequence> - plain-text two-digit decimal sequence identifier - increments with each send - probably not relevant
	# <end> - 03 hex (ascii heart)

	# examples:
	# FleetSync:
	#  poll 100:1001:  02 52 33 31 30 30 31 30 30 31 32 35 03   R3100100120  (sequence=20)
	#  poll 100:1002:  02 52 33 31 30 30 31 30 30 32 32 37 03   R3100100221  (sequence=21)
	# NEXEDGE:
	#  poll 03001:  02 67 52 33 55 30 33 30 30 31 30 36 03   gR3U0300108  (sequence=08) 
```

**Comment by caver456** [comment]
So there are a lot of places in the code where fleet and dev are assumed to exist.  Will have to figure out the best way to recode all of those.

Ultimately these pieces of code all revolve around fsLookup, which is a list of lists, each sublist having three elements: fleet, dev, callsign.  This is written to / read from radiolog_fleetsync.csv in the run dir.  (at the start of the session, .config/radiolog_fleetsync.csv is read to initialize the list - which can lead to long lookup list due to the new 'range' syntax - see if this impacts performance - maybe only save the non-default entries, or only the entries used during the session, in the run dir)

Probably the cleanest way to do it for nexedge is to add a sublist where the first element is blank and the second element is uid as a five-digit-string: [,01001,Team 1].  That way the list and the file are 'correct' and 'unambiguous'.

Then, other code can be put in place to deal with the interactions, e.g. what if any parts of the code should treat nexedge 01001 the same as fleetsync 100:1001.

**Comment by caver456** [comment]
Ready to resume work on this feature (June 13 2023), now that 3.7.0 is released and several bug fixes are in place.  Other major enhancements #598 and #391 should happen next, after this issue is finished.

**Comment by caver456** [comment]
Merged 3.7.0 into this issue's branch, but need to make sure those recent fixes and enhancements still work in this issue's branch since conflicts had to be resolved in radiolog.py, especially in fsLogUpdate and getCallsign.

**Comment by caver456** [comment]
Integration issues are probably best handled as comments and commits here, rather than new github issues.  For starters - this, and probably others to come, are likely due to the fact that pre-merge nxdn code was using all-strings-everywhere for fleet and dev, which is probably the way to go forward since NXDN UID is a string, while 3.7.0 was using int for fleet and dev.  Probably need to make some code changes to keep using str-everywhere.

```
105100:PARSING
105100:☻I110030011003001♥☻I010030011003001♥☻I$PKLSH,3916.1146,N,12101.5078,W,123456,A,100,3001,*2D♥
105100: line:☻I110030011003001♥☻I010030011003001♥☻I$PKLSH,3916.1146,N,12101.5078,W,123456,A,100,3001,*2D♥
105100:getCallsign called for FleetSync fleet=100 dev=3001
105100:found matching entry/entries:[[100, 3001, 'SAR 1']]
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 1923, in fsCheck
    self.fsParse()
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 2032, in fsParse
    callsign=self.getCallsign(fleet,dev)
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 2619, in getCallsign
    if len(matches)!=1 or len(matches[0][0])!=3: # no match
TypeError: object of type 'int' has no len()
```

**Comment by caver456** [comment]
improved #614 to also raise an exception (therefore try the next bak file in sequence) if a row doesn't have enough columns, indicating possible file corruption (and this case was also easier to create a test case for)

**Comment by caver456** [comment]
On incoming NXDN traffic:

```
073524:PARSING
073524:☻gI1U03004U03004♥☻$PKNSH,3916.3497,N,12101.3847,W,123456,A,U03004,*4C♥☻gI0U03004U03004♥
073524: line:☻gI1U03004U03004♥☻$PKNSH,3916.3497,N,12101.3847,W,123456,A,U03004,*4C♥☻gI0U03004U03004♥
073524:getCallsign called for NXDN UID=03004
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 1923, in fsCheck
    self.fsParse()
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 2050, in fsParse
    rprint("$PKNSH (NEXEDGE) detected containing CID: Unit ID = "+uid+"  -->  callsign="+callsign)
TypeError: can only concatenate str (not "NoneType") to str
```

Looks like getCallsign is returning None.

**Comment by caver456** [comment]
This was due to an indentation problem in getCallsign, which should have been caught during cleanup from the recent merge-commit.  Fixed for FS and for NXDN and committed to this branch, though initial call from KW-NXDN-... doesn't spawn CCD as it should.  Need to fix the code that checks for 'first non-mic-bump call from this device' which currently only triggers for fleetsync.

**Comment by caver456** [comment]
Getting closer - solved the issues above - but this looks really wacky:

214254:PARSING
214254:☻gI1U08005U08005♥☻$PKNSH,3916.1880,N,12101.4938,W,123456,A,U08005,*4C♥
214254: line:☻gI1U08005U08005♥☻$PKNSH,3916.1880,N,12101.4938,W,123456,A,U08005,*4C♥
214254:getCallsign called for NXDN UID=08005
Traceback (most recent call last):
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 1923, in fsCheck
    self.fsParse()
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 2047, in fsParse
    callsign=self.getCallsign(uid)
  File "C:\Users\caver\Documents\GitHub\radiolog\radiolog.py", line 2649, in getCallsign
    if int(entry[1])==uid:
ValueError: invalid literal for int() with base 10: 'U0800'

Two things: 1) U0800 (where's the last digit '5'?)  and 2) should the U be part of the uid or not?  either way it still needs to be a string, to capture any leading zero (08005).

**Comment by caver456** [comment]
Did another commit to address everything above.  Will need to add a full QA checklist at the top, to make sure all FS functionality is still working now / after all NXDN functionality is finished.  Will need to be plugged in to radios to perform the full QA, but, it seems to be good as much as I can test with fsTester.

**Comment by caver456** [comment]
At 91, here's a fresh check of progress that was made back in February:
- standard call from portable, on dTAC1, does show coordinates correctly in NED
- NXDN location polling works (previous reports of no TX from mobile on poll request have already been fixed in code and/or in the radio programming - this is with V6 on the office mobile, V5 on the portable) and a NED opens with good coordinates, but, the 'NEXEDGE Timeout' message box shows anyway.  Looks like self.fsAwaitingResponse isn't getting cleared.  Should be an easy fix...
- NXDN text (single device) does a TX from mobile, but no signs of life on the portable, and no ack from the portable, so the timeout message box shows.  A caught exception in getCallsign shows when the FleetSync Send Message dialog is opened - the dialog says 'Message for :03035 (no callsign):' - probably not related to failure to send/ack, but needs to be fixed either way:
```
191813:tab context menu requested: pos=PyQt5.QtCore.QPoint(83, 15)
191813:  i=2  tabRect=PyQt5.QtCore.QPoint(48, 37):PyQt5.QtCore.QPoint(95, 0)
191813:  extTeamName=z_Team00124  niceTeamName=Team 124
191816:ERROR in call to getCallsign: first argument must be 3 characters (FleetSync) or 5 characters (NEXEDGE): ""
191822:message:test2
191822:ERROR in call to getCallsign: first argument must be 3 characters (FleetSync) or 5 characters (NEXEDGE): ""
191822:sending text message to fleet= device=03035 (no callsign)
191822:com data: ☻F03035Jun29 19:18 test2♥
191822:fsLog:[['100', '3035', 'Team 123', False, 'Thu 19:16:24', 'COM5', 0, 2], ['', '03035', 'Team 124', False, 'Thu 19:17:36', 'COM5', 1, 3]]
191822:PARSING
191822:☻1♥
191822: line:☻1♥
191822:getCallsign called for NXDN UID=03035
191822:  found matching entry/entries:[['', '03035', 'Team 124']]
191822:newEntry called with these values:
191822:['1918', '', 'Team 124', 'NEXEDGE: NO RESPONSE from 03035 (Team 124)', '', '', 1688091502.9916675, '', '', '']
191823:NEXEDGE: NO RESPONSE from 03035 (Team 124)
191823:failed on preferred COM port; no alternate COM port available
```

**Comment by caver456** [comment]
Yup it was pretty easy to add the NXDN-vs-FS clause to sendText.  TX from the mobile happens correctly, the portable gets the text, the mobile receives the ack, and the delivery confirmation message box is shown.  Need to clean up these display issues before committing, but, this does seem like the radio programming is good to go for everything other than NXDN broadcast which hasn't been tried yet.
![image](https://github.com/ncssar/radiolog/assets/18752102/1f8ae4e1-c973-46ec-8718-4b5f7f201847)

**Comment by caver456** [comment]
Got NXDN broadcast to work.  Looking at radtext, guessing from the command strings but without actually looking at the data that radtext sends: replace the U with a G, and use device ID 00000 in the same manner as for FS:

```
205359:message:aaa
205359:broadcasting text message to all devices
205359:com data: ☻gFG00000Jun29 20:53 aaa♥
```

Two portables both receive the text on dTAC1.

**Comment by caver456** [comment]
did a few more cleanup commits, to make the message boxes more clear when sending text.

Next topic: how to modify the FleetSync Send Console dialog (spawned from the options dialog)?
1 - send to all: do we want to specify 'send to all fleetsync' vs 'send to all nxdn' vs 'send to all fleetsync and nxdn'?  Seems like cluttering up the GUI to allow this distinction wouldn't really be useful.  If the operator wants to broadcast, then they want to broadcast to all.  So - just send both - first broadcast to FS then broadcast to NXDN.  The code should be intelligent about deciding which com port/s to send those commands to - but - does it really matter if a digital broadcast command is sent to a radio that is set to an analog channel, or vice versa?  It could be important if it results in the same text getting sent twice to any given portable...
2 - sending to individual / multiple specific devices, and gps polling: option 1) add a radio button to select FS vs NXDN, then the Fleet ID field should be grayed out for NXDN; option 2) just add a note to leave the Fleet ID field blank for NXDN

**Comment by johnpictin** [comment]
Hi Tom,

Just a suggestion on this. The radio operator shouldn't be bothered with
asking is this an nxdn or fleetsync radio. They should either be
broadcasting to all radios or selecting a radio from a team tab or a
directory of radios. The software should look up the radio and decide what
format to use based on the Device ID/Fleetsync ID in the lookup table.

This could be accomplished by having an editable per radio callsign where
an individual's name or callsign would be entered. Right now, when you go
into the fleetsync menu on a team tab, you see the Fleetsync ID. An
editable user friendly call sign or individuals name would be ideal. It
would be an additional field in the NED and potentially the change team
screen as well as a column in the fleetsync display. But it would be nice
for the operator to be able to associate a radio with an individual as well
as have them grouped by team. Once the radio is assigned to an individual
it's Device ID is not very important to the comms operator. It would make
digital messaging and polling simpler because you could clearly understand
who is who, especially when you wind up with many radios on a team
assignment. It would be easy to have an alphabetical list of all members
who are equipped with radios and are on the task and to be able to message
them directly. Or when selecting a team you would see the names of the
radio equipped users on that assignment

On our team we do not have enough radios to assign one to each member. Our
SOP is to always have a minimum of 2 radios per team, usually one with the
TL and a second with the member they designate to handle radio comms for
the group. Those radios are dynamic and change hands as the task
progresses, from one team assignment to another. So being able to modify
the radio call sign as well as the team designation would be important. I
hope I have explained myself clearly.

John

**Comment by caver456** [comment]
Hi John - I think we're probably talking about the same thing and mostly came to the same conclusions?

For broadcasting, yes I think it's best to leave the FS Send Console button as-is and not make the operator choose between FS and NXDN:

![image](https://github.com/ncssar/radiolog/assets/18752102/b491ce7d-2209-47d7-bdc8-f79cef9b8de5)

Here's the context menu for a team with multiple FS devices and multiple NXDN devices:

![image](https://github.com/ncssar/radiolog/assets/18752102/783bef05-2844-435b-9dd0-b8e7a44ab05b)

The idea about a separate sub-callsign per device makes sense, though it seems even more niche: it seems very rare to want to send a text to e.g. Joe on team 1 but not to Susan on team 1 (so I think the send-to-individual-device entries in that context menu would rarely be used - they are mostly there for completeness).  It seems rare enough that if we needed to do that, we'd find a way within IC to figure out who has what device number: probably just looking on the equipment sign-out sheet (or looking up the person's SAR# if it's one of the folks that has a long-term issued radio, which we could tell by the device ID thousands digit).  Granted, that's just our team and there are probably teams where that isn't an option, so I'll add an issue for it but seems like pretty low priority.  Adding sub-callsigns and a way to manage them may be a fairly invasive code change adding a fair amount of GUI complexity.

Seems like it's also going to be pretty rare that the FleetSync Send Console (from the options menu) is used to send text to individual radio/s.  That function would probably always be done from the team tab context menu.  But, if the operator is going to know enough to be sending by ID using the FleetSync Send Console, then they would know whether they want to send to FS or to NXDN.

Let me know if I misinterpreted - did that cover your suggestions?  Thanks

**Comment by caver456** [comment]
Made a few commits that should address the FleetSync Send Console topic.  (leaving it with that same name is probably OK due to real estate concerns - a more correct name would be 'FleetSync / NEXEDGE Send Console')

Here are some iterations of the Send Console dialog with all the recently-committed callbacks in place:

![image](https://github.com/ncssar/radiolog/assets/18752102/5eaa4c26-90b9-4b19-9896-486ddb4c4a43)

There are a few checkboxes remaining in the desired functionality set - it's possible those are already working correctly, so, initial QA next week at the station will tell the tale.
